# Train every NFLELO model, end to end

A personal notebook: run it any time to refresh the nflverse data and retrain **every** model in the project
on the development seasons, then fit this season's production models and print this week's predictions.
The walkthrough (`00_nflelo_walkthrough.ipynb`) *loads* saved results. This one *trains*.

**How to run** (from the repo root; the `.venv` has every dependency, including PyTorch):

```
# one-time setup (Python 3.13; torch has no wheels for 3.15 yet)
uv venv --python 3.13 .venv && uv pip install --python .venv/bin/python -r requirements-m6.txt
brew install libomp                      # macOS only, needed by LightGBM

# run it (writes the outputs back into this file)
TRAIN_MODE=full  .venv/bin/jupyter nbconvert --to notebook --execute --inplace notebooks/train_all_models.ipynb
TRAIN_MODE=quick .venv/bin/jupyter nbconvert --to notebook --execute --inplace notebooks/train_all_models.ipynb
# or:  scripts/train_all.sh [quick|full]
```

**What it will not do.** The 2020-2025 seasons are a spent holdout. Nothing here scores them again: every model
is trained and scored on its development seasons, and the locked holdout results are only *loaded* from
`experiments/runs/` and shown for context. Nothing is written to the run registry, the live ledger, the saved
fourth-down engine, `site/data/`, `outputs/` or `data/games.csv`: run records are redirected to a gitignored folder
(`data/raw/ml/_train_all_runs/`), and the last cell checks that git sees no new changes.

**Quick vs full.** `quick` skips the slow hyper-parameter searches (they re-find the constants already fixed in
the code), the 18-minute playoff-simulation backtest, and most of the fourth-down bootstrap; it retrains every
model with the settings already in the code. `full` also reruns the searches and uses the original bootstrap size, so
every "matches the record" table is comparable cell for cell.

**Saved outputs.** The outputs stored in this file come from a `full` run (73 minutes wall time on an Apple-silicon Mac; the fourth-down bootstrap alone is 37 minutes of it). `quick` takes about 25 minutes.

In [1]:
import os

# ---- configuration ----------------------------------------------------------------------------------
# TRAIN_MODE and REFRESH_DATA can be set from the shell (see above); edit the defaults here if you prefer.
MODE = os.environ.get("TRAIN_MODE", "full")              # "quick" or "full"
REFRESH_DATA = os.environ.get("REFRESH_DATA", "1") != "0"  # pull fresh nflverse data first
assert MODE in ("quick", "full"), "MODE must be 'quick' or 'full'"
FULL = MODE == "full"
print(f"MODE = {MODE}, REFRESH_DATA = {REFRESH_DATA}")

MODE = full, REFRESH_DATA = True

In [2]:
# ---- setup and helpers ------------------------------------------------------------------------------
import contextlib, importlib, json, re, shutil, subprocess, sys, time, warnings
from pathlib import Path

import numpy as np
import pandas as pd
from IPython.display import Markdown, display

warnings.filterwarnings("ignore")
pd.set_option("display.width", 200, "display.max_columns", 40, "display.max_colwidth", 80)

ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "nflelo").is_dir())
os.chdir(ROOT)
for p in (str(ROOT), str(ROOT / "scripts")):
    if p not in sys.path:
        sys.path.insert(0, p)

from nflelo import config, data as elo_data                      # noqa: E402
from nflelo.elo import run_elo                                    # noqa: E402
from nflelo.ml import data as mldata, registry                    # noqa: E402
from nflelo.ml.eval import windows                                # noqa: E402

REAL_RUNS = registry.RUNS_DIR                                     # the committed registry: read-only here
CAPTURE = ROOT / "data" / "raw" / "ml" / "_train_all_runs"        # gitignored: where this notebook's run records go
shutil.rmtree(CAPTURE, ignore_errors=True)
CAPTURE.mkdir(parents=True)


def git_dirty() -> set:
    out = subprocess.run(["git", "status", "--porcelain", "--untracked-files=all"], cwd=ROOT,
                         capture_output=True, text=True, check=True).stdout
    return set(out.splitlines())


GIT_AT_START = git_dirty()
RUNS_AT_START = sorted(p.name for p in REAL_RUNS.glob("*.json"))

# Every script writes its scored runs through registry.log_run. Send them to CAPTURE instead of the registry,
# and refuse anything that touches the locked 2020-2025 seasons.
_real_log_run = registry.log_run


def _captured_log_run(*args, **kw):
    seasons = kw.get("seasons")
    if seasons is not None and windows.touches_holdout(seasons):
        raise RuntimeError(f"refusing to log a run on locked holdout seasons {seasons}")
    kw["runs_dir"] = CAPTURE
    return _real_log_run(*args, **kw)


registry.log_run = _captured_log_run

SECTION_SECONDS: dict = {}
ALL_RECS: list = []


@contextlib.contextmanager
def section(name: str):
    t0 = time.perf_counter()
    try:
        yield
    finally:
        SECTION_SECONDS[name] = SECTION_SECONDS.get(name, 0.0) + time.perf_counter() - t0
        print(f"\n[{name}: {SECTION_SECONDS[name]:.0f}s]")


def run_main(module: str, argv=(), fn: str = "main", *args, **kw):
    # Run one script function (default: its main) with the given argv; returns the run records it produced.
    mod = importlib.import_module(module)
    before = {p.name for p in CAPTURE.glob("*.json")}
    old_argv, old_dir = sys.argv, registry.RUNS_DIR
    sys.argv, registry.RUNS_DIR = [f"{module}.py", *argv], CAPTURE   # so "runs written to ..." messages are true
    try:
        rc = getattr(mod, fn)(*args, **kw)
    except SystemExit as e:
        rc = e.code
    finally:
        sys.argv, registry.RUNS_DIR = old_argv, old_dir
    if rc not in (0, None, True):
        raise RuntimeError(f"{module}.{fn}{tuple(argv)} returned {rc!r}")
    recs = [json.loads(p.read_text()) for p in sorted(CAPTURE.glob("*.json")) if p.name not in before]
    ALL_RECS.extend(recs)
    return recs


# ---- "does it match the record?" ----------------------------------------------------------------------
SKIP_KEYS = re.compile(r"timing|seconds|_s$|elapsed|runtime", re.I)
PRIMARY = ["brier", "crps", "mse", "mae", "brier_playoffs", "ope_epa.diff", "logloss", "wmse", "loglik"]


def flat(d, prefix=""):
    out = {}
    for k, v in (d or {}).items():
        key = f"{prefix}{k}"
        if SKIP_KEYS.search(key):
            continue
        if isinstance(v, bool):
            continue
        if isinstance(v, (int, float)) and np.isfinite(v):
            out[key] = float(v)
        elif isinstance(v, dict):
            out.update(flat(v, key + "."))
    return out


def registry_ref(name: str, label: str):
    best = None
    for r in registry.load_runs(REAL_RUNS):
        if r["name"] == name and r["label"] == label and not r.get("holdout"):
            if best is None or r["timestamp"] >= best["timestamp"]:
                best = r
    return best


TOL_ABS, TOL_REL = 5e-5, 2e-3
QUICK_EXPECTED = {"m7a_audit"}    # depends on the bootstrap size, which quick mode shrinks     # nondeterminism allowance: |diff| <= max(5e-5, 0.2% of the record value)


def match_table(recs, title="Retrained vs the committed development record"):
    rows = []
    for r in recs:
        ref = registry_ref(r["name"], r["label"])
        if ref is None:
            rows.append({"run": r["name"], "key metric": "", "record": np.nan, "retrained": np.nan, "diff": np.nan,
                         "largest diff": np.nan, "on metric": "", "same games": "", "status": "NO RECORD"})
            continue
        a, b = flat(r["metrics"]), flat(ref["metrics"])
        keys = [k for k in b if k in a and k != "n"]
        bad = [k for k in keys if abs(a[k] - b[k]) > max(TOL_ABS, TOL_REL * abs(b[k]))]
        key = next((k for k in PRIMARY if k in keys), keys[0] if keys else None)
        worst = max(keys, key=lambda k: abs(a[k] - b[k]) / max(TOL_ABS, TOL_REL * abs(b[k]))) if keys else None
        if worst is not None and abs(a[worst] - b[worst]) < 1e-12:
            worst = None                                      # exact match on every metric
        same_n = r["n"] == ref["n"]
        rows.append({"run": r["name"], "key metric": key or "", "record": b.get(key, np.nan),
                     "retrained": a.get(key, np.nan), "diff": a[key] - b[key] if key else np.nan,
                     "largest diff": a[worst] - b[worst] if worst else 0.0, "on metric": worst or "(none: exact)",
                     "same games": "yes" if r["games_hash"] == ref["games_hash"] else ("n only" if same_n else "NO"),
                     "status": "OK" if not bad and same_n else
                               ("differs (quick bootstrap)" if not FULL and r["name"] in QUICK_EXPECTED else "DIFFERS")})
    t = pd.DataFrame(rows)
    n_ok = int(t["status"].isin(["OK"]).sum())
    n_exp = int(t["status"].str.startswith("differs (quick").sum())
    display(Markdown(f"**{title}**: {n_ok} of {len(t)} runs match "
                     f"(tolerance max({TOL_ABS:g}, {TOL_REL:.1%} of the record) on every metric)"
                     + (f"; {n_exp} expected to differ in quick mode." if n_exp else ".")))
    display(t.style.format({c: "{:.5f}" for c in ("record", "retrained", "diff", "largest diff")}, na_rep="").hide(axis="index"))
    return t


# ---- locked holdout results, loaded not recomputed --------------------------------------------------
def _fmt_metrics(r):
    bits = []
    for k, v in (r.get("metrics") or {}).items():
        if k == "n" or SKIP_KEYS.search(k):
            continue
        if isinstance(v, bool):
            continue
        if isinstance(v, (int, float)):
            bits.append(f"{k} {v:.4f}")
        elif isinstance(v, dict) and "diff" in v and "ci_low" in v:
            bits.append(f"{k} {v['diff']:+.4f} [{v['ci_low']:+.4f}, {v['ci_high']:+.4f}]")
        elif isinstance(v, dict) and "brier" in v:
            bits.append(f"{k}: brier {v['brier']:.4f}" + (f", ECE {v['cal']['ece']:.4f}" if "cal" in v else ""))
    for k, v in (r.get("comparisons") or {}).items():
        if isinstance(v, dict) and "diff" in v and "ci_low" in v:
            bits.append(f"{k} {v['diff']:+.4f} [{v['ci_low']:+.4f}, {v['ci_high']:+.4f}]")
    return "; ".join(bits[:9]) or "(descriptive tables only; see the record)"


def locked_holdout(prefixes, only=None, skip=(), note=""):
    # Show the committed 2020-2025 holdout records whose names start with a prefix (latest per name).
    latest = {}
    for r in registry.load_runs(REAL_RUNS):
        if r.get("holdout") and r["name"].startswith(tuple(prefixes)) and (only is None or r["name"].endswith(tuple(only))) and not r["name"].endswith(tuple(skip) or ("\0",)):
            if r["name"] not in latest or r["timestamp"] >= latest[r["name"]]["timestamp"]:
                latest[r["name"]] = r
    rows = []
    for name, r in sorted(latest.items()):
        parts = name.split("_")
        shown = "_".join([parts[0]] + parts[2:]) if r["label"] == "holdout" and len(parts) > 2 else name
        lo, hi = r["window"]["seasons"]
        rows.append({"record": shown, "seasons": f"{lo}-{hi}", "n": r["n"], "result (diff = [95% CI])": _fmt_metrics(r),
                     "committed": r["timestamp"][:10]})
    display(Markdown("**Locked 2020-2025 holdout, loaded from `experiments/runs/` (not recomputed)**" + (f". {note}" if note else "")))
    display(pd.DataFrame(rows).style.hide(axis="index"))


def runtime_note():
    return "  ·  ".join(f"{k}: {v:.0f}s" for k, v in SECTION_SECONDS.items())


print(f"repo root: {ROOT}")
print(f"registry: {len(RUNS_AT_START)} committed run files (read-only); this notebook's runs go to {CAPTURE.relative_to(ROOT)}/")
print(f"git changes before the run: {sorted(GIT_AT_START) or 'none'}")

repo root: /Users/walker_tracy/Desktop/Old Projects/NFLELO
registry: 167 committed run files (read-only); this notebook's runs go to data/raw/ml/_train_all_runs/
git changes before the run: ['?? notebooks/train_all_models.ipynb', '?? scripts/train_all.sh']

## 1. Data refresh

Pulls the newest nflverse schedule (and, in `full`, the current and previous season of every cached dataset),
then rebuilds `games` and the Elo ratings **in memory**. `data/games.csv` and `outputs/` are not touched: the
rebuilt games go to `data/raw/train_all/` (gitignored) and the scripts below are pointed at them.

In [3]:
CURRENT = 2026                      # the season the production models predict (scripts/ml_predict.SEASON)

with section("1. Data refresh"):
    if REFRESH_DATA:
        plan = {s: (list(mldata.FETCHERS) if FULL else ["pbp", "schedules"]) for s in ([CURRENT - 1, CURRENT] if FULL else [CURRENT])}
        rows = []
        for season, datasets in plan.items():
            for ds in datasets:
                if ds == "players" or season < mldata.FIRST_SEASON.get(ds, 0):
                    continue
                try:
                    r = mldata.refresh_one(ds, season)
                    rows.append({"dataset": ds, "season": season, "rows": r["rows"], "previous rows": r["old_rows"],
                                 "changed": r["changed"]})
                except Exception as e:                                   # e.g. a dataset not published yet
                    rows.append({"dataset": ds, "season": season, "rows": None, "previous rows": None,
                                 "changed": f"skipped: {type(e).__name__}"})
        if FULL:
            r = mldata.refresh_one("players", mldata.SNAPSHOT_SEASON)
            rows.append({"dataset": "players", "season": "snapshot", "rows": r["rows"], "previous rows": r["old_rows"],
                         "changed": r["changed"]})
        display(pd.DataFrame(rows))
    else:
        print("REFRESH_DATA is off: using the cached nflverse files.")

    sched_raw = elo_data.fetch_nflverse_schedules(refresh=REFRESH_DATA)
    nflverse = elo_data.nflverse_to_games(sched_raw)
    elo538 = elo_data.load_538_games(seasons=(1970, 2022))
    games_fresh = elo_data.build_games(elo538, nflverse)
    FRESH_DIR = ROOT / "data" / "raw" / "train_all"
    FRESH_DIR.mkdir(parents=True, exist_ok=True)
    FRESH_CSV = FRESH_DIR / "games_fresh.csv"
    games_fresh.to_csv(FRESH_CSV, index=False)
    # From here on every script that calls nflelo.data.load_games() reads the freshly built games.
    elo_data.load_games = lambda csv=FRESH_CSV: pd.read_csv(csv, parse_dates=["date"])

    committed = pd.read_csv(config.GAMES_CSV, parse_dates=["date"])
    new_ids = set(games_fresh["game_id"]) - set(committed["game_id"])
    both = games_fresh[games_fresh["game_id"].isin(committed["game_id"])].merge(
        committed, on="game_id", suffixes=("", "_old"))
    changed = both[(both["home_score"] != both["home_score_old"]) | (both["away_score"] != both["away_score_old"])]
    print(f"games rebuilt in memory: {len(games_fresh):,} games, seasons {games_fresh.season.min()}-{games_fresh.season.max()}")
    print(f"vs committed data/games.csv: {len(new_ids)} new finished games, {len(changed)} games with a changed score")

    ELO, ELO_STATE = run_elo(games_fresh, config.DEFAULT_CONFIG)
    last = ELO.sort_values(["date", "game_id"]).iloc[-1]
    print(f"Elo v2 rebuilt through {last['date']:%Y-%m-%d} (season {last['season']} week {last['week']}); "
          f"current home-field advantage {ELO_STATE['hfa']:.1f} Elo points")
    long = pd.concat([ELO[["date", "game_id", "home", "home_post"]].set_axis(["date", "game_id", "team", "post"], axis=1),
                      ELO[["date", "game_id", "away", "away_post"]].set_axis(["date", "game_id", "team", "post"], axis=1)])
    now_ratings = long.sort_values(["date", "game_id"], kind="stable").groupby("team")["post"].last().sort_values(ascending=False)
    display(now_ratings.head(10).round(0).astype(int).rename("Elo").to_frame().T)

           dataset    season      rows  previous rows              changed
0              pbp      2025   48771.0        48771.0                False
1        schedules      2025     285.0          285.0                False
2     player_stats      2025   19422.0        19422.0                False
3     depth_charts      2025  554215.0       554215.0                False
4         injuries      2025    6068.0         6068.0                False
5   rosters_weekly      2025   46849.0        46849.0                False
6    participation      2025   45184.0        45184.0                False
7              pbp      2026   16212.0        16212.0                False
8        schedules      2026     272.0          272.0                False
9     player_stats      2026    6417.0         6417.0                False
10    depth_charts      2026  673227.0       673227.0                False
11        injuries      2026    1789.0         1789.0                False
12  rosters_weekly      2026   15327.0        15327.0                False
13   participation      2026       NaN            NaN  skipped: ValueError
14         players  snapshot   24854.0        24854.0                False

games rebuilt in memory: 13,777 games, seasons 1970-2026
vs committed data/games.csv: 14 new finished games, 0 games with a changed score
Elo v2 rebuilt through 2026-10-18 (season 2026 week 6); current home-field advantage 35.0 Elo points

team    SF   BUF   MIN   SEA   JAX   DEN    NE    KC   CHI   PIT
Elo   1643  1633  1624  1609  1603  1602  1594  1577  1554  1550

[1. Data refresh: 4s]

## 2. Elo v2 and the baselines (coin flip, home-team rate, betting market)

Elo is the project's starting model: K 20, season regression 0.40, a home-field advantage that is learned online.
The betting market (vig removed) is only a benchmark, never a feature. Elo itself has no training step beyond the
rebuild above, so this section scores it, with the three baselines, on the development seasons 2006-2019. Result
on record: Elo scores 0.2178 Brier vs the market's 0.2106.

In [4]:
import ml_baselines

with section("2. Elo v2 + baselines"):
    # DEV 2006-2019 only. (The script's own reproduction step re-scores 2010-2025, so it is not called.)
    recs_baselines = run_main("ml_baselines", [], "dev", elo_data.load_games(), True)
match_table(recs_baselines)
locked_holdout(["m3_"], only=("elo_v2", "market"),
               note="Elo and the market on the 1,615 holdout games that have moneylines.")

== (b) DEV, REG 2006-2019: identical games (those with moneylines) ==
3450 of 3584 REG games have moneylines; all four baselines are scored on those 3450.
model            n    brier  logloss     acc     ece
market        3450   0.2106   0.6096   0.663  0.0182
elo_v2        3450   0.2178   0.6255   0.641  0.0154
home_rate     3450   0.2451   0.6847   0.566  0.0069
coin_flip     3450   0.2493   0.6931   0.434  0.0659

Elo v2 minus market, Brier: +0.0072, 95% paired bootstrap CI [+0.0044, +0.0101] (2000 reps, seed 20261003); excludes zero.
Note: Elo v2 was tuned on 1980-2009, so 2006-2009 are in-sample for Elo.

[2. Elo v2 + baselines: 0s]

**Retrained vs the committed development record**: 4 of 4 runs match (tolerance max(5e-05, 0.2% of the record) on every metric).

**Locked 2020-2025 holdout, loaded from `experiments/runs/` (not recomputed)**. Elo and the market on the 1,615 holdout games that have moneylines.

## 3. M3: the game model (A4s) and the no-Elo study

Win probability from a logistic regression on Elo, opponent-adjusted EPA and a starting-quarterback adjustment.
The script runs the whole experiment ladder A0-A6 and picks A4s by the one-standard-error rule. **Passed** on the
locked seasons (Brier 0.2195 vs Elo 0.2231). The no-Elo study asks what the model would score without Elo; it is
descriptive and was never a pass/fail test.

In [5]:
with section("3a. M3 game model ladder"):
    recs_m3 = []
    if FULL:
        recs_m3 += run_main("ml_tune_ratings")           # re-tunes the EPA-rating and QB knobs on 2000-2005
    recs_m3 += run_main("ml_m3")
match_table(recs_m3)

== Stage 1: team ratings, next-week EPA margin, REG 2000-2005 ==
1518 games, 102 weekly fits per setting, grid 8 lambda x 10 half-life x 5 rho = 400 settings
Predict-zero MSE: 0.14822
 lam  half_life     rho    n     mse  mse_zero      r2    corr
 100         48 0.25000 1518 0.13043   0.14822 0.12002 0.35075
 100         24 0.25000 1518 0.13046   0.14822 0.11979 0.35026
 100         96 0.25000 1518 0.13046   0.14822 0.11976 0.35048
 100         12 0.50000 1518 0.13051   0.14822 0.11947 0.34905
 100       1000 0.25000 1518 0.13054   0.14822 0.11927 0.34987
 100         16 0.50000 1518 0.13054   0.14822 0.11923 0.34883
 100         16 0.25000 1518 0.13061   0.14822 0.11879 0.34873
 100         24 0.50000 1518 0.13074   0.14822 0.11788 0.34704
  50         48 0.25000 1518 0.13076   0.14822 0.11779 0.34964
  50         96 0.25000 1518 0.13077   0.14822 0.11767 0.34936
Chosen: lambda 100, half_life 48 weeks, rho 0.25
  best MSE by lam: 25: 0.13121, 50: 0.13076, 100: 0.13043, 200: 0.13083, 400: 0.13244, 800: 0.13492, 1600: 0.13753, 3200: 0.14076
  best MSE by half_life: 2: 0.13604, 4: 0.13228, 6: 0.13115, 8: 0.13078, 12: 0.13051, 16: 0.13054, 24: 0.13046, 48: 0.13043, 96: 0.13046, 1000: 0.13054
  best MSE by rho: 0.1: 0.13116, 0.25: 0.13043, 0.5: 0.13051, 0.75: 0.13081, 1: 0.13107

== Stage 2: QB shrinkage k (half_life 48, rho 0.25) ==
3036 starter-games, 87125 dropbacks. Replacement priors (EPA/dropback): 2000: -0.053, 2001: -0.128, 2002: -0.091, 2003: -0.066, 2004: -0.089, 2005: -0.118
   k  n_games  dropbacks    wmse
  25     3036      87125 0.11073
  50     3036      87125 0.10955
 100     3036      87125 0.10918
 200     3036      87125 0.11027
 300     3036      87125 0.11170
 400     3036      87125 0.11301
 600     3036      87125 0.11512
 800     3036      87125 0.11668
1200     3036      87125 0.11878
1600     3036      87125 0.12013
3200     3036      87125 0.12265
Chosen: k = 100 pseudo-dropbacks

Timing: load 0.4s, stage 1 23.4s (400 settings), stage 2 0.3s, total 24.1s
Code constants (opponent_adjust.TUNED, qb.TUNED_K): match
Run written to data/raw/ml/_train_all_runs/20261020T031409Z_m3_tune_ratings.json

DEV 2006-2019: 3450 REG games with moneylines (training: REG 2001..S-1, 1272 games before 2006).
Elo v2 on these games: Brier 0.2178. Feature build 2.5s (elo 0.0s, raw_epa 0.2s, ratings 0.2s, qb 2.1s)

A0 check: logistic on elo_logit 0.21783 vs Elo 0.21782 (diff +0.00001; tolerance 0.001)

Ladder, DEV 2006-2019 (n = 3450). diff = model minus Elo v2 Brier, 95% paired bootstrap CI (2,000 reps, seed 20261003); 1SE = within one SE of the best.
step model                                            brier  logloss    acc     ece  diff vs Elo [95% CI]          1SE
     Elo v2 (reference)                              0.2178   0.6255  0.641  0.0154
A0   elo_logit                                       0.2178   0.6257  0.645  0.0175  +0.0000 [-0.0003, +0.0003]
A1   elo_logit + raw_epa_margin                      0.2180   0.6260  0.645  0.0165  +0.0001 [-0.0002, +0.0005]
A2   elo_logit + adj_epa_margin                      0.2177   0.6254  0.644  0.0124  -0.0002 [-0.0008, +0.0005]
A3   elo_logit + adj_pass_margin + adj_rush_margin   0.2180   0.6262  0.639  0.0157  +0.0002 [-0.0006, +0.0010]
A4   elo_logit + adj_epa_margin + qb_home + qb_awa   0.2150   0.6195  0.647  0.0125  -0.0028 [-0.0045, -0.0011]   yes
A4s  elo_logit + adj_epa_margin + qb_diff            0.2151   0.6197  0.647  0.0114  -0.0027 [-0.0043, -0.0011]   yes *
A4b  elo_logit + adj_epa_margin + qb_last_home + q   0.2171   0.6244  0.647  0.0111  -0.0007 [-0.0018, +0.0005]
A4bs elo_logit + adj_epa_margin + qb_last_diff       0.2172   0.6244  0.643  0.0116  -0.0006 [-0.0016, +0.0004]
A5   elo_logit + adj_epa_margin + qb_home + qb_awa   0.2150   0.6194  0.650  0.0087  -0.0028 [-0.0046, -0.0011]   yes
A6   GBM: elo_logit + adj_epa_margin + qb_home + q   0.2172   0.6253  0.652  0.0199  -0.0006 [-0.0032, +0.0020]
Market (benchmark): Brier 0.2106

Best DEV Brier: A5 (0.21498). Within one SE of it: ['A4', 'A4s', 'A5'].
Chosen by the one-SE rule: A4s (3 features, logistic).
M3 acceptance (beats Elo with CI excluding 0, ECE < 0.02): PASS (diff -0.0027 [-0.0043, -0.0011], ECE 0.0114)
QB news (A4 minus A4b Brier): -0.0021 [-0.0035, -0.0008]
QB news (A4s minus A4bs Brier): -0.0021 [-0.0033, -0.0010]
Symmetric vs separate QB terms (A4s minus A4 Brier): +0.00009 [-0.00016, +0.00034]

Coefficients of A4s, model for 2019 (trained on 2001-2018, n = 4600); range over the 14 DEV refits in brackets:
  intercept       +0.0482  [+0.0209, +0.0915]
  elo_logit       +0.8415  [+0.6190, +0.8707]   per 1 SD (0.760): +0.639 log-odds
  adj_epa_margin  +1.0869  [+0.8725, +2.2145]   per 1 SD (0.138): +0.150 log-odds
  qb_delta_diff   +3.6071  [+2.7402, +3.7590]   per 1 SD (0.063): +0.229 log-odds
  sign check: all coefficients have the expected sign in every refit

Timing: load 1.1s, features 2.5s, ladder fits 7.4s, total 11.1s. One weekly update (2019 week 10, 13 games: Elo, ratings, QB values, predict): 0.50s, plus 0.00s for the once-a-season refit. Features match the ladder: True.

10 runs written to data/raw/ml/_train_all_runs/

[3a. M3 game model ladder: 37s]

**Retrained vs the committed development record**: 11 of 11 runs match (tolerance max(5e-05, 0.2% of the record) on every metric).

                run key metric    record  retrained  diff  largest diff      on metric same games status
0   m3_tune_ratings        mse  0.130425   0.130425   0.0           0.0  (none: exact)        yes     OK
1             m3_A0      brier  0.217827   0.217827   0.0           0.0  (none: exact)        yes     OK
2             m3_A1      brier  0.217956   0.217956   0.0           0.0  (none: exact)        yes     OK
3             m3_A2      brier  0.217653   0.217653   0.0           0.0  (none: exact)        yes     OK
4             m3_A3      brier  0.218017   0.218017   0.0           0.0  (none: exact)        yes     OK
5             m3_A4      brier  0.214999   0.214999   0.0           0.0  (none: exact)        yes     OK
6            m3_A4b      brier  0.217145   0.217145   0.0           0.0  (none: exact)        yes     OK
7           m3_A4bs      brier  0.217175   0.217175   0.0           0.0  (none: exact)        yes     OK
8            m3_A4s      brier  0.215086   0.215086   0.0           0.0  (none: exact)        yes     OK
9             m3_A5      brier  0.214984   0.214984   0.0           0.0  (none: exact)        yes     OK
10            m3_A6      brier  0.217238   0.217238   0.0           0.0  (none: exact)        yes     OK

In [6]:
with section("3b. M3 no-Elo study"):
    recs_noelo = run_main("ml_m3_noelo")
match_table(recs_noelo)
locked_holdout(["m3_"], only=("A4s", "A4bs"), note="A4s is the live headline model; A4bs is its Wednesday-only twin.")

DEV 2006-2019: n = 3450, games hash 52b8194df3a2ebf4. Elo v2 Brier 0.2178; A4s recomputed 0.2151.

id  model                                                        brier  logloss    acc    ece    p95  vs Elo [95% CI]             vs A4s [95% CI]
N1  adj_epa_margin                                              0.2209   0.6329  0.635 0.0183 0.0241  +0.0030 [+0.0007, +0.0053]  +0.0058 [+0.0036, +0.0080]
N2  adj_epa_margin + qb_delta_diff                              0.2183   0.6275  0.643 0.0163 0.0250  +0.0005 [-0.0021, +0.0033]  +0.0033 [+0.0016, +0.0049]
N3  adj_epa_margin + qb_delta_diff + rest_diff + neutral        0.2182   0.6271  0.647 0.0120 0.0250  +0.0004 [-0.0024, +0.0033]  +0.0031 [+0.0013, +0.0049]
N4  adj_pass_margin + adj_rush_margin + qb_delta_diff + rest_   0.2188   0.6284  0.643 0.0104 0.0243  +0.0010 [-0.0018, +0.0039]  +0.0037 [+0.0019, +0.0056]
N5  GBM: adj_pass_margin + adj_rush_margin + qb_delta_diff +    0.2209   0.6339  0.640 0.0208 0.0260  +0.0030 [-0.0003, +0.0066]  +0.0058 [+0.0032, +0.0085]
N6  adj_epa_margin + qb_delta_diff + raw_epa_margin             0.2185   0.6277  0.645 0.0133 0.0251  +0.0007 [-0.0021, +0.0034]  +0.0034 [+0.0015, +0.0052]

Best no-Elo model: N3 (Brier 0.2182).
(a) Brier by week bucket:
  weeks       n       N3       N2      A4s      Elo  N3 - Elo [95% CI]             A4s - N2 [95% CI]
  1-4       751   0.2277   0.2281   0.2243   0.2229  +0.0049 [-0.0005, +0.0100]    -0.0038 [-0.0073, -0.0004]
  5-9       969   0.2167   0.2173   0.2126   0.2140  +0.0027 [-0.0022, +0.0080]    -0.0047 [-0.0081, -0.0016]
  10-18    1730   0.2149   0.2147   0.2125   0.2178  -0.0028 [-0.0066, +0.0011]    -0.0022 [-0.0045, +0.0004]
  all    A4s - N2: -0.0033 [-0.0049, -0.0016]
(b) corr(logit p_N3, elo_logit) = 0.861; by bucket 1-4 0.850, 5-9 0.862, 10-18 0.869; corr with A4s logit 0.943; adj_epa_margin vs elo_logit 0.902
(c) A4s refit on one week bucket's training rows (2019 fit ± bootstrap SE; median over the 14 refits):
  weeks 1-4    n_train  1107  intercept +0.023 ±0.108 (+0.199)  elo_logit +1.041 ±0.252 (+0.474)  adj_epa_margin -0.361 ±1.182 (+2.502)  qb_delta_diff +2.581 ±1.276 (+3.347)
  weeks 5-9    n_train  1248  intercept +0.031 ±0.092 (+0.031)  elo_logit +0.976 ±0.208 (+0.961)  adj_epa_margin +0.795 ±1.039 (+0.631)  qb_delta_diff +3.418 ±1.257 (+1.890)
  weeks 10-18  n_train  2245  intercept +0.067 ±0.074 (+0.025)  elo_logit +0.683 ±0.143 (+0.695)  adj_epa_margin +2.029 ±0.903 (+1.861)  qb_delta_diff +3.942 ±0.732 (+3.391)

6 runs written to data/raw/ml/_train_all_runs/

[3b. M3 no-Elo study: 12s]

**Retrained vs the committed development record**: 6 of 6 runs match (tolerance max(5e-05, 0.2% of the record) on every metric).

**Locked 2020-2025 holdout, loaded from `experiments/runs/` (not recomputed)**. A4s is the live headline model; A4bs is its Wednesday-only twin.

## 4. M3b: Kalman-filter team strength (C2d, the shadow model)

A state-space rating that carries uncertainty, added to Elo and the QB term (C2d). On the development seasons it
beat A4s by 0.00095 Brier, just short of the pre-set bar, so it was **never run on the holdout**. It runs as a
shadow model in the live 2026 ledger. The `full` mode re-tunes the Kalman knobs on 2000-2005 (about 4 minutes).

In [7]:
with section("4. M3b Kalman (C2d)"):
    recs_m3b = []
    if FULL:
        recs_m3b += run_main("ml_m3b", ["tune"])
    recs_m3b += run_main("ml_m3b", ["dev"])
match_table(recs_m3b)
print("No holdout result exists for M3b by design: it narrowly missed its development bar.")

== Kalman tuning, 2000-2005 (filter from 1999), 1586 games, 195.1s, 7983 evaluations ==
starts (joint loglik, margin loglik, knobs):
    -6072.17   -6368.85  q_week 0.8516, gamma 0.4948, q_season 11.73, sigma_m 12.36, sigma_e 13.49, rho 0.807, scale 39.84, q_hfa 0.0003818
    -6071.90   -6368.60  q_week 0.7137, gamma 0.4836, q_season 14.42, sigma_m 12.36, sigma_e 13.51, rho 0.8071, scale 39.88, q_hfa 0.0003564
    -6071.90   -6368.59  q_week 0.7215, gamma 0.4832, q_season 14.43, sigma_m 12.36, sigma_e 13.52, rho 0.8071, scale 39.92, q_hfa 0.0003456
    -6071.95   -6368.80  q_week 0.7285, gamma 0.4842, q_season 14.11, sigma_m 12.36, sigma_e 13.35, rho 0.8066, scale 39.49, q_hfa 0.0003647
margin-only optima from the same starts (not used; flat ridge):
    -6371.25  q_week 0.899, gamma 0.5332, q_season 5.444, sigma_m 12.55, sigma_e 15.87, rho 0.6572, scale 58.77, q_hfa 0.01058
    -6372.55  q_week 0.1288, gamma 0.5534, q_season 1.082, sigma_m 13.21, sigma_e 20.99, rho -0.8819, scale 29.21, q_hfa 0
    -6365.92  q_week 0.5838, gamma 0.4446, q_season 14.53, sigma_m 12.48, sigma_e 12.82, rho 0.9698, scale 91.56, q_hfa 0.0005989
    -6369.15  q_week 0.8147, gamma 0.5586, q_season 7.33, sigma_m 12.51, sigma_e 12.76, rho 0.9764, scale 44.42, q_hfa 0.08897
CHOSEN: q_week 0.72155, gamma 0.48317, q_season 14.431, sigma_m 12.361, sigma_e 13.519, rho 0.80707, scale 39.918, q_hfa 0.00034558, epa_home 0.0085843
margin loglik per game -4.0155 (constant-mean model -4.0921); RMSE 13.419 vs SD 14.485; at bounds: none
in words: weekly_sd 0.85 pts, season_sd_17wk 3.50 pts, offseason_sd 3.80 pts, hfa_sd_per_season 0.08 pts

== QB extras tuning ==
baseline (M3 QB value, k 100) on 2000-2005: wMSE 0.10918 (3036 starter-games); M3 code path 0.10918

(b) experience offsets (-0.0541, 0.0159, 0.1412, 0.0648) (buckets (0, 100, 500, 2000), starter-games [210, 409, 506, 1911]): wMSE 0.10839 vs 0.10918

(b2) experience offsets tuned on the 351 changed-starter games: (-0.0651, 0.08, 0.0329, 0.0318): wMSE 0.11445 vs 0.11588 without (the all-starter offsets give 0.11505 here)

(c) aging (peak, slope before, slope after) = (31.0, 0.14, 0.0): wMSE 0.10810 vs 0.10918; 4361 of 4361 QB-games have a birth date; top 5:
 peak  before  after     wmse
   31    0.14  0.000 0.108098
   31    0.12  0.000 0.108109
   31    0.14 -0.005 0.108109
   31    0.12 -0.005 0.108120
   31    0.14 -0.010 0.108121

(a) CPOE composite on 2007-2008 (1024 starter-games): weight 0.01 EPA/dropback per CPOE point, k 400 attempts: wMSE 0.11457 vs 0.11490 without; top 5:
 cpoe_weight  cpoe_k     wmse
      0.0100     400 0.114573
      0.0075     200 0.114576
      0.0150     800 0.114580
      0.0125     400 0.114592
      0.0050     100 0.114593
QB tuning 15.1s

Freeze in code:
  kalman.TUNED = KalmanConfig(q_week=0.72155, gamma=0.48317, q_season=14.431, sigma_m=12.361, sigma_e=13.519, rho=0.80707, scale=39.918, q_hfa=0.00034558, epa_home=0.0085843)
  qb.TUNED_EXTRAS = QBExtras(cpoe_weight=0.01, cpoe_k=400, experience=(-0.0541, 0.0159, 0.1412, 0.0648), aging=(31.0, 0.14, 0.0))
  qb.TUNED_EXPERIENCE_CHANGED = (-0.0651, 0.08, 0.0329, 0.0318)

DEV 2006-2019: n = 3450, games hash 52b8194df3a2ebf4. Features 8.6s (elo 0.0s, raw_epa 0.2s, ratings 0.2s, qb 2.1s, kalman 0.2s, qb_extras 5.9s)
A4s reproduction: Brier 0.21509 on n = 3450 (M3 ladder 0.2151, n 3450)

C1 grid (DEV-tuned w0; early = max(0, 1 - (week - 1) / w0)), Brier and minus A4s:
  w0    1: 0.21517  +0.0001 [-0.0001, +0.0002]  <- best
  w0    2: 0.21523  +0.0001 [-0.0001, +0.0004]
  w0    3: 0.21539  +0.0003 [+0.0001, +0.0006]
  w0    4: 0.21546  +0.0004 [+0.0001, +0.0006]
  w0    5: 0.21547  +0.0004 [+0.0001, +0.0006]
  w0    6: 0.21549  +0.0004 [+0.0001, +0.0007]
  w0    8: 0.21547  +0.0004 [+0.0001, +0.0007]
  w0   10: 0.21543  +0.0003 [+0.0000, +0.0007]
  w0   12: 0.21542  +0.0003 [+0.0000, +0.0007]
  w0   18: 0.21537  +0.0003 [-0.0000, +0.0006]

Ladder, DEV 2006-2019, n = 3450. diff = step minus A4s (paired bootstrap, 2,000 reps, seed 20261003). ECE ok = at or below the 95th percentile of a calibrated forecaster at this n.
step                     brier  logloss    acc     ece    p95  ok  vs A4s [95% CI]              1SE
A4s                     0.2151   0.6197  0.647  0.0114  0.025   y  +0.0000 [+0.0000, +0.0000]
A4bs                    0.2172   0.6244  0.643  0.0116  0.025   y  +0.0021 [+0.0010, +0.0033]
C1                      0.2152   0.6199  0.647  0.0126  0.025   y  +0.0001 [-0.0001, +0.0002]
C2a                     0.2146   0.6186  0.654  0.0187  0.027   y  -0.0005 [-0.0020, +0.0010]
C2b                     0.2141   0.6175  0.649  0.0130  0.026   y  -0.0009 [-0.0019, +0.0001]   yes
C2c                     0.2145   0.6185  0.651  0.0226  0.026   y  -0.0006 [-0.0021, +0.0010]
C2d                     0.2141   0.6175  0.650  0.0142  0.026   y  -0.0010 [-0.0019, +0.0000]   yes *
C2k                     0.2167   0.6235  0.647  0.0148  0.025   y  +0.0016 [-0.0005, +0.0035]
KF                      0.2167   0.6236  0.645  0.0168  0.025   y  +0.0016 [-0.0004, +0.0036]
C3a                     0.2150   0.6196  0.644  0.0163  0.025   y  -0.0000 [-0.0002, +0.0001]
C3b                     0.2157   0.6210  0.643  0.0140  0.026   y  +0.0006 [+0.0000, +0.0013]
C3c                     0.2155   0.6206  0.643  0.0146  0.026   y  +0.0004 [+0.0000, +0.0008]
C3d                     0.2152   0.6199  0.647  0.0129  0.025   y  +0.0001 [-0.0004, +0.0006]
C3abc                   0.2161   0.6217  0.646  0.0145  0.025   y  +0.0010 [+0.0003, +0.0016]
C4_C2d+C3a              0.2141   0.6175  0.650  0.0152  0.026   y  -0.0010 [-0.0019, -0.0000]   yes

Elo v2                  0.2178   0.6255  0.641  0.0154
Market                  0.2106   0.6096  0.663  0.0182
Leak alarm (better than A4s by more than 0.006): none
Best: C4_C2d+C3a (0.21410). Within one SE: ['C2b', 'C2d', 'C4_C2d+C3a']. CHOSEN (one-SE rule): C2d.
Acceptance on DEV (beats A4s, CI excludes 0, one-sided ECE check): FAIL

Splits (Brier; step minus A4s [95% CI]; market Brier on the same games):
  A4s:
    weeks_1_4 n751 0.2243 +0.0000 [+0.0000, +0.0000] mkt 0.2198
    weeks_5_9 n969 0.2126 +0.0000 [+0.0000, +0.0000] mkt 0.2095
    weeks_10_18 n1730 0.2125 +0.0000 [+0.0000, +0.0000] mkt 0.2072
    changed n664 0.2150 +0.0000 [+0.0000, +0.0000] mkt 0.2072
    unchanged n2786 0.2151 +0.0000 [+0.0000, +0.0000] mkt 0.2114
  C1:
    weeks_1_4 n751 0.2246 +0.0003 [-0.0004, +0.0010] mkt 0.2198
    weeks_5_9 n969 0.2126 +0.0000 [-0.0000, +0.0001] mkt 0.2095
    weeks_10_18 n1730 0.2125 +0.0000 [-0.0001, +0.0001] mkt 0.2072
    changed n664 0.2153 +0.0003 [-0.0003, +0.0009] mkt 0.2072
    unchanged n2786 0.2151 +0.0000 [-0.0001, +0.0001] mkt 0.2114
  C2a:
    weeks_1_4 n751 0.2244 +0.0002 [-0.0026, +0.0028] mkt 0.2198
    weeks_5_9 n969 0.2138 +0.0012 [-0.0016, +0.0041] mkt 0.2095
    weeks_10_18 n1730 0.2108 -0.0017 [-0.0038, +0.0005] mkt 0.2072
    changed n664 0.2158 +0.0008 [-0.0026, +0.0043] mkt 0.2072
    unchanged n2786 0.2143 -0.0008 [-0.0024, +0.0009] mkt 0.2114

  C2b:
    weeks_1_4 n751 0.2238 -0.0005 [-0.0022, +0.0012] mkt 0.2198
    weeks_5_9 n969 0.2124 -0.0001 [-0.0020, +0.0017] mkt 0.2095
    weeks_10_18 n1730 0.2109 -0.0016 [-0.0030, -0.0001] mkt 0.2072
    changed n664 0.2149 -0.0001 [-0.0023, +0.0020] mkt 0.2072
    unchanged n2786 0.2140 -0.0011 [-0.0022, -0.0000] mkt 0.2114
  C2c:
    weeks_1_4 n751 0.2243 -0.0000 [-0.0028, +0.0026] mkt 0.2198
    weeks_5_9 n969 0.2137 +0.0011 [-0.0017, +0.0041] mkt 0.2095
    weeks_10_18 n1730 0.2108 -0.0017 [-0.0038, +0.0005] mkt 0.2072
    changed n664 0.2160 +0.0010 [-0.0023, +0.0045] mkt 0.2072
    unchanged n2786 0.2142 -0.0009 [-0.0026, +0.0007] mkt 0.2114
  C2d:
    weeks_1_4 n751 0.2237 -0.0006 [-0.0023, +0.0011] mkt 0.2198
    weeks_5_9 n969 0.2124 -0.0002 [-0.0019, +0.0016] mkt 0.2095
    weeks_10_18 n1730 0.2109 -0.0016 [-0.0029, -0.0002] mkt 0.2072
    changed n664 0.2150 -0.0000 [-0.0021, +0.0021] mkt 0.2072
    unchanged n2786 0.2139 -0.0012 [-0.0022, -0.0001] mkt 0.2114
  KF:
    weeks_1_4 n751 0.2232 -0.0011 [-0.0049, +0.0026] mkt 0.2198
    weeks_5_9 n969 0.2152 +0.0026 [-0.0009, +0.0061] mkt 0.2095
    weeks_10_18 n1730 0.2148 +0.0023 [-0.0009, +0.0054] mkt 0.2072
    changed n664 0.2248 +0.0098 [+0.0037, +0.0162] mkt 0.2072
    unchanged n2786 0.2148 -0.0003 [-0.0023, +0.0017] mkt 0.2114

  C3a:
    weeks_1_4 n751 0.2244 +0.0001 [-0.0000, +0.0003] mkt 0.2198
    weeks_5_9 n969 0.2125 -0.0000 [-0.0002, +0.0002] mkt 0.2095
    weeks_10_18 n1730 0.2124 -0.0001 [-0.0003, +0.0001] mkt 0.2072
    changed n664 0.2151 +0.0001 [-0.0003, +0.0006] mkt 0.2072
    unchanged n2786 0.2150 -0.0001 [-0.0002, +0.0000] mkt 0.2114
  C3b:
    weeks_1_4 n751 0.2256 +0.0013 [-0.0003, +0.0028] mkt 0.2198
    weeks_5_9 n969 0.2129 +0.0003 [-0.0009, +0.0015] mkt 0.2095
    weeks_10_18 n1730 0.2131 +0.0006 [-0.0003, +0.0014] mkt 0.2072
    changed n664 0.2177 +0.0027 [+0.0001, +0.0052] mkt 0.2072
    unchanged n2786 0.2153 +0.0002 [-0.0003, +0.0007] mkt 0.2114
  C3c:
    weeks_1_4 n751 0.2242 -0.0001 [-0.0011, +0.0010] mkt 0.2198
    weeks_5_9 n969 0.2132 +0.0006 [-0.0001, +0.0012] mkt 0.2095
    weeks_10_18 n1730 0.2131 +0.0006 [+0.0001, +0.0011] mkt 0.2072
    changed n664 0.2157 +0.0007 [-0.0007, +0.0021] mkt 0.2072
    unchanged n2786 0.2155 +0.0004 [+0.0000, +0.0007] mkt 0.2114
  C3d:
    weeks_1_4 n751 0.2245 +0.0002 [-0.0011, +0.0015] mkt 0.2198
    weeks_5_9 n969 0.2124 -0.0001 [-0.0010, +0.0008] mkt 0.2095
    weeks_10_18 n1730 0.2127 +0.0002 [-0.0006, +0.0008] mkt 0.2072
    changed n664 0.2152 +0.0002 [-0.0019, +0.0023] mkt 0.2072
    unchanged n2786 0.2152 +0.0001 [-0.0003, +0.0005] mkt 0.2114

  C3abc:
    weeks_1_4 n751 0.2254 +0.0011 [-0.0007, +0.0029] mkt 0.2198
    weeks_5_9 n969 0.2134 +0.0008 [-0.0004, +0.0021] mkt 0.2095
    weeks_10_18 n1730 0.2135 +0.0010 [+0.0001, +0.0019] mkt 0.2072
    changed n664 0.2181 +0.0031 [+0.0004, +0.0056] mkt 0.2072
    unchanged n2786 0.2156 +0.0005 [-0.0001, +0.0011] mkt 0.2114
  C4_C2d+C3a:
    weeks_1_4 n751 0.2238 -0.0004 [-0.0021, +0.0012] mkt 0.2198
    weeks_5_9 n969 0.2124 -0.0002 [-0.0019, +0.0017] mkt 0.2095
    weeks_10_18 n1730 0.2108 -0.0017 [-0.0030, -0.0003] mkt 0.2072
    changed n664 0.2151 +0.0001 [-0.0020, +0.0022] mkt 0.2072
    unchanged n2786 0.2139 -0.0012 [-0.0023, -0.0002] mkt 0.2114

Wednesday twin C2d_last: Brier 0.2161; minus A4bs -0.0011 [-0.0021, -0.0001]; minus A4s +0.0010 [-0.0005, +0.0026]

Coefficients (last DEV refit; range over the 14 refits):
  A4s (2019 fit, n 4600): intercept +0.048 [+0.021, +0.091], elo_logit +0.842 [+0.619, +0.871], adj_epa_margin +1.087 [+0.872, +2.214], qb_delta_diff +3.607 [+2.740, +3.759]
  C1 (2019 fit, n 4600): intercept +0.047 [+0.018, +0.091], elo_logit +0.840 [+0.613, +0.867], adj_epa_margin +1.055 [+0.842, +2.256], qb_delta_diff +3.616 [+2.740, +3.763], elo_logit_x_early1 +0.088 [-0.393, +0.294], adj_epa_margin_x_early1 +0.475 [-1.536, +1.115]
  C2a (2019 fit, n 4600): intercept -0.033 [-0.063, +0.017], kf_margin +0.151 [+0.110, +0.151], adj_epa_margin -0.622 [-0.632, +0.742], qb_delta_diff +3.359 [+2.559, +3.541]
  C2b (2019 fit, n 4600): intercept -0.064 [-0.086, -0.009], elo_logit +0.452 [+0.194, +0.511], kf_margin +0.101 [+0.065, +0.129], adj_epa_margin -0.899 [-0.899, +0.521], qb_delta_diff +3.481 [+2.616, +3.647]
  C2c (2019 fit, n 4600): intercept +0.001 [-0.039, +0.001], kf_margin +0.137 [+0.122, +0.137], qb_delta_diff +3.373 [+2.520, +3.554]
  C2d (2019 fit, n 4600): intercept -0.014 [-0.051, -0.014], elo_logit +0.433 [+0.176, +0.496], kf_margin +0.083 [+0.068, +0.114], qb_delta_diff +3.495 [+2.592, +3.665]
  C2k (2019 fit, n 4600): intercept +0.001 [-0.034, +0.001], kf_margin +0.135 [+0.121, +0.136]
  C3abc (2019 fit, n 4600): intercept +0.053 [+0.024, +0.095], elo_logit +0.822 [+0.612, +0.858], adj_epa_margin +1.047 [+0.817, +2.160], qb_delta_diff_abc +2.454 [+1.694, +3.232]
corr(kf_margin, elo_logit) on DEV = 0.942; corr(kf_margin, adj_epa_margin) = 0.941
corr(qb_delta_diff, variant): a 0.996, b 0.907, c 0.966, d 0.935, abc 0.880

Timing: features 8.6s, ladder 0.9s, total 15.5s

16 runs written to data/raw/ml/_train_all_runs/

[4. M3b Kalman (C2d): 227s]

**Retrained vs the committed development record**: 18 of 18 runs match (tolerance max(5e-05, 0.2% of the record) on every metric).

No holdout result exists for M3b by design: it narrowly missed its development bar.

## 5. M4: margin model and playoff odds

The margin model predicts the whole distribution of a game's final margin, aware of key numbers like 3 and 7. It
**failed** its holdout primary (the improvement over Elo's spread was within noise) but powers spreads and the
simulation. The playoff odds (20,000 simulated seasons with real NFL tiebreakers) **passed**. `quick` retrains the
margin model only; `full` also re-tunes the rest-week uncertainty and backtests the simulation on 2006-2019
(about 18 minutes).

In [8]:
with section("5. M4 margin + playoff odds"):
    recs_m4 = run_main("ml_m4", ["margin"])
    if FULL:
        recs_m4 += run_main("ml_m4", ["tune"])
        recs_m4 += run_main("ml_m4", ["backtest"])
match_table(recs_m4)
locked_holdout(["m4_"])

== Margin model, DEV 2006-2019, REG games with moneylines: n = 3450 (games hash 52b8194df3a2ebf4) ==
MAE  model 10.667   Elo spread (elo_diff/25) 10.731   market spread 10.487
     model minus Elo  -0.064 [-0.118, -0.009]  excludes zero
     model minus market +0.180 [+0.096, +0.268]
CRPS normal_continuous 7.6638   normal 7.6620   keynum 7.6480
     shape rule: best keynum; other minus best +0.0141 (SE 0.0042) -> chosen: keynum
shape      brier  logloss    acc    ece  ECE null 5-95%  minus A4s Brier [95% CI]       1SE
normal    0.2151   0.6199  0.648 0.0129  [0.010, 0.026]  +0.00004 [-0.00039, +0.00051]   yes
keynum    0.2153   0.6203  0.648 0.0141  [0.009, 0.025]  +0.00018 [-0.00036, +0.00074]   yes
A4s       0.2151   0.6197  0.647 0.0114  [0.010, 0.025]
Home team beats our spread, by predicted spread (5-95% range of a fair coin at that n):
  (-inf, -7]   n   213  0.545  [0.441, 0.559]  inside
  (-7, -3]     n   416  0.524  [0.459, 0.541]  inside
  (-3, 0]      n   573  0.475  [0.466, 0.534]  inside
  (0, 3]       n   689  0.501  [0.469, 0.531]  inside
  (3, 7]       n   825  0.487  [0.472, 0.528]  inside
  (7, inf]     n   734  0.466  [0.470, 0.530]  OUTSIDE
MAE by season (model / Elo / market): 2006: 11.10 / 11.11 / 11.07; 2007: 11.15 / 11.19 / 10.82; 2008: 11.12 / 11.34 / 11.25; 2009: 11.46 / 11.54 / 11.25; 2010: 11.18 / 11.09 / 10.83; 2011: 10.58 / 10.69 / 10.47; 2012: 11.15 / 11.23 / 10.87; 2013: 9.86 / 9.95 / 9.82; 2014: 11.41 / 11.39 / 11.39; 2015: 10.06 / 10.12 / 10.13; 2016: 9.21 / 9.30 / 9.02; 2017: 10.43 / 10.73 / 10.08; 2018: 10.39 / 10.33 / 9.98; 2019: 10.48 / 10.53 / 10.21
2019 fit: intercept +0.419, elo_logit +5.962, adj_epa_margin +9.088, qb_delta_diff +27.005, sigma 13.52
2 runs written to data/raw/ml/_train_all_runs/

total 4s
== tau_rest tuning on DEV 2006-2019: weeks (4, 8, 12, 16), shape keynum, grid 0 to 8 by 0.5, 5,000 sims per start, one-SE rule (smallest tau) ==

  tune 2006 week 4: 210 games left, state 0.3s, 17 x 5,000 sims 15.6s

  tune 2006 week 8: 156 games left, state 0.3s, 17 x 5,000 sims 15.2s

  tune 2006 week 12: 96 games left, state 0.3s, 17 x 5,000 sims 15.4s

  tune 2006 week 16: 32 games left, state 0.3s, 17 x 5,000 sims 14.9s

  tune 2007 week 4: 208 games left, state 0.3s, 17 x 5,000 sims 17.0s

  tune 2007 week 8: 153 games left, state 0.3s, 17 x 5,000 sims 16.4s

  tune 2007 week 12: 96 games left, state 0.3s, 17 x 5,000 sims 14.7s

  tune 2007 week 16: 32 games left, state 0.3s, 17 x 5,000 sims 10.9s

  tune 2008 week 4: 209 games left, state 0.3s, 17 x 5,000 sims 16.7s

  tune 2008 week 8: 154 games left, state 0.3s, 17 x 5,000 sims 16.2s

  tune 2008 week 12: 96 games left, state 0.3s, 17 x 5,000 sims 15.3s

  tune 2008 week 16: 32 games left, state 0.4s, 17 x 5,000 sims 12.9s

  tune 2009 week 4: 208 games left, state 0.4s, 17 x 5,000 sims 15.7s

  tune 2009 week 8: 153 games left, state 0.4s, 17 x 5,000 sims 14.4s

  tune 2009 week 12: 96 games left, state 0.4s, 17 x 5,000 sims 14.6s

  tune 2009 week 16: 32 games left, state 0.3s, 17 x 5,000 sims 13.3s

  tune 2010 week 4: 208 games left, state 0.4s, 17 x 5,000 sims 17.0s

  tune 2010 week 8: 152 games left, state 0.4s, 17 x 5,000 sims 16.6s

  tune 2010 week 12: 96 games left, state 0.4s, 17 x 5,000 sims 15.9s

  tune 2010 week 16: 32 games left, state 0.4s, 17 x 5,000 sims 15.2s

  tune 2011 week 4: 208 games left, state 0.4s, 17 x 5,000 sims 16.6s

  tune 2011 week 8: 153 games left, state 0.4s, 17 x 5,000 sims 15.7s

  tune 2011 week 12: 96 games left, state 0.4s, 17 x 5,000 sims 14.4s

  tune 2011 week 16: 32 games left, state 0.4s, 17 x 5,000 sims 14.0s

  tune 2012 week 4: 208 games left, state 0.4s, 17 x 5,000 sims 17.6s

  tune 2012 week 8: 152 games left, state 0.4s, 17 x 5,000 sims 17.6s

  tune 2012 week 12: 96 games left, state 0.5s, 17 x 5,000 sims 14.1s

  tune 2012 week 16: 32 games left, state 0.4s, 17 x 5,000 sims 13.9s

  tune 2013 week 4: 208 games left, state 0.5s, 17 x 5,000 sims 16.4s

  tune 2013 week 8: 149 games left, state 0.5s, 17 x 5,000 sims 15.5s

  tune 2013 week 12: 94 games left, state 0.5s, 17 x 5,000 sims 15.4s

  tune 2013 week 16: 32 games left, state 0.5s, 17 x 5,000 sims 12.4s

  tune 2014 week 4: 208 games left, state 0.5s, 17 x 5,000 sims 17.3s

  tune 2014 week 8: 150 games left, state 0.5s, 17 x 5,000 sims 14.5s

  tune 2014 week 12: 95 games left, state 0.5s, 17 x 5,000 sims 14.9s

  tune 2014 week 16: 32 games left, state 0.5s, 17 x 5,000 sims 13.3s

  tune 2015 week 4: 208 games left, state 0.5s, 17 x 5,000 sims 16.1s

  tune 2015 week 8: 151 games left, state 0.5s, 17 x 5,000 sims 14.6s

  tune 2015 week 12: 96 games left, state 0.5s, 17 x 5,000 sims 14.8s

  tune 2015 week 16: 32 games left, state 0.5s, 17 x 5,000 sims 13.3s

  tune 2016 week 4: 208 games left, state 0.5s, 17 x 5,000 sims 16.5s

  tune 2016 week 8: 149 games left, state 0.5s, 17 x 5,000 sims 15.4s

  tune 2016 week 12: 95 games left, state 0.6s, 17 x 5,000 sims 13.0s

  tune 2016 week 16: 32 games left, state 0.5s, 17 x 5,000 sims 11.8s

  tune 2017 week 4: 209 games left, state 0.6s, 17 x 5,000 sims 17.0s

  tune 2017 week 8: 150 games left, state 0.6s, 17 x 5,000 sims 17.9s

  tune 2017 week 12: 96 games left, state 0.6s, 17 x 5,000 sims 15.6s

  tune 2017 week 16: 32 games left, state 0.5s, 17 x 5,000 sims 14.4s

  tune 2018 week 4: 208 games left, state 0.6s, 17 x 5,000 sims 14.9s

  tune 2018 week 8: 149 games left, state 0.6s, 17 x 5,000 sims 14.1s

  tune 2018 week 12: 95 games left, state 0.6s, 17 x 5,000 sims 12.9s

  tune 2018 week 16: 32 games left, state 0.6s, 17 x 5,000 sims 10.3s

  tune 2019 week 4: 208 games left, state 0.6s, 17 x 5,000 sims 15.2s

  tune 2019 week 8: 150 games left, state 0.6s, 17 x 5,000 sims 14.6s

  tune 2019 week 12: 94 games left, state 0.6s, 17 x 5,000 sims 14.3s

  tune 2019 week 16: 32 games left, state 0.6s, 17 x 5,000 sims 13.3s

made-playoffs Brier by tau_rest (n = 1792 team-starts; SE from a team-start bootstrap):
     0  0.1214  minus best +0.00200  SE 0.00069
   0.5  0.1214  minus best +0.00195  SE 0.00067
     1  0.1212  minus best +0.00175  SE 0.00064
   1.5  0.1212  minus best +0.00179  SE 0.00059
     2  0.1206  minus best +0.00124  SE 0.00052
   2.5  0.1204  minus best +0.00103  SE 0.00043
     3  0.1199  minus best +0.00046  SE 0.00034
   3.5  0.1199  minus best +0.00045  SE 0.00025
     4  0.1196  minus best +0.00016  SE 0.00016
   4.5  0.1194  minus best +0.00000  SE 0.00000  within  <- best  <- chosen
     5  0.1195  minus best +0.00013  SE 0.00016  within
   5.5  0.1196  minus best +0.00014  SE 0.00023  within
     6  0.1195  minus best +0.00007  SE 0.00033  within
   6.5  0.1197  minus best +0.00026  SE 0.00042  within
     7  0.1197  minus best +0.00034  SE 0.00051  within
   7.5  0.1200  minus best +0.00058  SE 0.00060  within
     8  0.1204  minus best +0.00097  SE 0.00068

chosen tau_rest = 4.5 (best 4.5). ECE at the chosen tau (null 5-95%):
  playoffs  Brier 0.1194  ECE 0.016  [0.012, 0.028]  inside
  division  Brier 0.0881  ECE 0.023  [0.011, 0.025]  inside
  seed1     Brier 0.0320  ECE 0.012  [0.006, 0.015]  inside
  reach_sb  Brier 0.0465  ECE 0.014  [0.004, 0.015]  inside
  win_sb    Brier 0.0280  ECE 0.002  [0.002, 0.010]  OUTSIDE

total 865s

  backtest 2006 week 4: 210 games left, state 0.3s, 2 x 10,000 sims 3.9s

  backtest 2006 week 8: 156 games left, state 0.3s, 2 x 10,000 sims 3.7s

  backtest 2006 week 12: 96 games left, state 0.3s, 2 x 10,000 sims 3.7s

  backtest 2006 week 16: 32 games left, state 0.3s, 2 x 10,000 sims 3.5s

  backtest 2007 week 4: 208 games left, state 0.4s, 2 x 10,000 sims 4.2s

  backtest 2007 week 8: 153 games left, state 0.3s, 2 x 10,000 sims 4.0s

  backtest 2007 week 12: 96 games left, state 0.3s, 2 x 10,000 sims 3.5s

  backtest 2007 week 16: 32 games left, state 0.3s, 2 x 10,000 sims 2.6s

  backtest 2008 week 4: 209 games left, state 0.3s, 2 x 10,000 sims 4.2s

  backtest 2008 week 8: 154 games left, state 0.3s, 2 x 10,000 sims 3.9s

  backtest 2008 week 12: 96 games left, state 0.3s, 2 x 10,000 sims 3.7s

  backtest 2008 week 16: 32 games left, state 0.3s, 2 x 10,000 sims 3.1s

  backtest 2009 week 4: 208 games left, state 0.4s, 2 x 10,000 sims 3.9s

  backtest 2009 week 8: 153 games left, state 0.4s, 2 x 10,000 sims 3.5s

  backtest 2009 week 12: 96 games left, state 0.4s, 2 x 10,000 sims 3.5s

  backtest 2009 week 16: 32 games left, state 0.4s, 2 x 10,000 sims 3.2s

  backtest 2010 week 4: 208 games left, state 0.4s, 2 x 10,000 sims 4.2s

  backtest 2010 week 8: 152 games left, state 0.4s, 2 x 10,000 sims 4.0s

  backtest 2010 week 12: 96 games left, state 0.4s, 2 x 10,000 sims 3.9s

  backtest 2010 week 16: 32 games left, state 0.4s, 2 x 10,000 sims 3.4s

  backtest 2011 week 4: 208 games left, state 0.4s, 2 x 10,000 sims 4.1s

  backtest 2011 week 8: 153 games left, state 0.4s, 2 x 10,000 sims 3.7s

  backtest 2011 week 12: 96 games left, state 0.4s, 2 x 10,000 sims 3.4s

  backtest 2011 week 16: 32 games left, state 0.4s, 2 x 10,000 sims 3.3s

  backtest 2012 week 4: 208 games left, state 0.4s, 2 x 10,000 sims 4.4s

  backtest 2012 week 8: 152 games left, state 0.4s, 2 x 10,000 sims 4.3s

  backtest 2012 week 12: 96 games left, state 0.4s, 2 x 10,000 sims 3.3s

  backtest 2012 week 16: 32 games left, state 0.5s, 2 x 10,000 sims 3.3s

  backtest 2013 week 4: 208 games left, state 0.5s, 2 x 10,000 sims 4.0s

  backtest 2013 week 8: 149 games left, state 0.5s, 2 x 10,000 sims 3.7s

  backtest 2013 week 12: 94 games left, state 0.5s, 2 x 10,000 sims 3.6s

  backtest 2013 week 16: 32 games left, state 0.4s, 2 x 10,000 sims 2.8s

  backtest 2014 week 4: 208 games left, state 0.5s, 2 x 10,000 sims 4.5s

  backtest 2014 week 8: 150 games left, state 0.5s, 2 x 10,000 sims 3.5s

  backtest 2014 week 12: 95 games left, state 0.5s, 2 x 10,000 sims 3.5s

  backtest 2014 week 16: 32 games left, state 0.5s, 2 x 10,000 sims 3.2s

  backtest 2015 week 4: 208 games left, state 0.6s, 2 x 10,000 sims 4.0s

  backtest 2015 week 8: 151 games left, state 0.5s, 2 x 10,000 sims 3.5s

  backtest 2015 week 12: 96 games left, state 0.5s, 2 x 10,000 sims 3.5s

  backtest 2015 week 16: 32 games left, state 0.5s, 2 x 10,000 sims 3.1s

  backtest 2016 week 4: 208 games left, state 0.6s, 2 x 10,000 sims 4.1s

  backtest 2016 week 8: 149 games left, state 0.5s, 2 x 10,000 sims 3.7s

  backtest 2016 week 12: 95 games left, state 0.5s, 2 x 10,000 sims 3.1s

  backtest 2016 week 16: 32 games left, state 0.5s, 2 x 10,000 sims 2.8s

  backtest 2017 week 4: 209 games left, state 0.6s, 2 x 10,000 sims 4.2s

  backtest 2017 week 8: 150 games left, state 0.6s, 2 x 10,000 sims 4.4s

  backtest 2017 week 12: 96 games left, state 0.6s, 2 x 10,000 sims 3.7s

  backtest 2017 week 16: 32 games left, state 0.5s, 2 x 10,000 sims 3.5s

  backtest 2018 week 4: 208 games left, state 0.6s, 2 x 10,000 sims 4.1s

  backtest 2018 week 8: 149 games left, state 0.6s, 2 x 10,000 sims 3.4s

  backtest 2018 week 12: 95 games left, state 0.6s, 2 x 10,000 sims 3.3s

  backtest 2018 week 16: 32 games left, state 0.6s, 2 x 10,000 sims 2.5s

  backtest 2019 week 4: 208 games left, state 0.6s, 2 x 10,000 sims 3.8s

  backtest 2019 week 8: 150 games left, state 0.7s, 2 x 10,000 sims 3.7s

  backtest 2019 week 12: 94 games left, state 0.6s, 2 x 10,000 sims 3.4s

  backtest 2019 week 16: 32 games left, state 0.6s, 2 x 10,000 sims 3.2s

== Playoff odds, DEV (in-sample for tau, descriptive) 2006-2019: 56 starts, 1792 team-starts, tau_rest 4.5 vs 0 ==
outcome    Brier tau  Brier 0  diff [95% CI, team-starts]    [95% CI, by season]        ECE  null 5-95%
playoffs      0.1195   0.1213  -0.0017 [-0.0031, -0.0004]     [-0.0044, +0.0008]    0.018  [0.012, 0.028]
division      0.0882   0.0880  +0.0001 [-0.0011, +0.0013]     [-0.0017, +0.0022]    0.021  [0.011, 0.025]
seed1         0.0320   0.0317  +0.0003 [-0.0005, +0.0010]     [-0.0008, +0.0014]    0.012  [0.006, 0.015]
reach_sb      0.0465   0.0458  +0.0007 [-0.0001, +0.0016]     [-0.0004, +0.0019]    0.014  [0.004, 0.015]
win_sb        0.0281   0.0283  -0.0002 [-0.0006, +0.0002]     [-0.0008, +0.0003]    0.002  [0.002, 0.010]  (below p05)
made playoffs by start week (Brier tau / tau 0, ECE): week 4: 0.1732 / 0.1764, 0.043; week 8: 0.1383 / 0.1398, 0.032; week 12: 0.1041 / 0.1056, 0.031; week 16: 0.0625 / 0.0632, 0.026
made playoffs by season (Brier tau / tau 0): 2006: 0.1301 / 0.1341; 2007: 0.0969 / 0.0914; 2008: 0.1878 / 0.1999; 2009: 0.1061 / 0.1061; 2010: 0.0836 / 0.0758; 2011: 0.1167 / 0.1161; 2012: 0.1333 / 0.1385; 2013: 0.1145 / 0.1169; 2014: 0.1073 / 0.1055; 2015: 0.1035 / 0.1083; 2016: 0.1389 / 0.1431; 2017: 0.0980 / 0.0963; 2018: 0.1542 / 0.1607; 2019: 0.1028 / 0.1049

total 231s

[5. M4 margin + playoff odds: 1100s]

**Retrained vs the committed development record**: 5 of 5 runs match (tolerance max(5e-05, 0.2% of the record) on every metric).

**Locked 2020-2025 holdout, loaded from `experiments/runs/` (not recomputed)**

## 6. M5: box-score player values and pregame lineups

Per-player values from game-level stats, summed over the expected lineup, tested as extra inputs to A4s on
2012-2019. A **negative result**: no step beats A4s (every confidence interval includes zero), so the player
features do not enter the game model. No holdout was run (nothing to test). `full` also re-tunes the value knobs
on 2001-2008.

In [9]:
with section("6. M5 box-score player values"):
    recs_m5 = []
    if FULL:
        recs_m5 += run_main("ml_tune_players")
    recs_m5 += run_main("ml_m5")
match_table(recs_m5)
print("No holdout result exists for M5 by design: nothing beat A4s on the development window.")

Inputs 1999-2008 loaded and credited in 5.2s: 125,134 player-games.
Era gaps (component recorded = 1):
season   1999  2000  2001  2002  2003  2004  2005  2006  2007  2008
db          1     1     1     1     1     1     1     1     1     1
rush        1     1     1     1     1     1     1     1     1     1
rb_recv     1     1     1     1     0     0     0     0     0     0
recv        1     1     1     1     0     0     0     0     0     0
sack        1     1     1     1     1     1     1     1     1     1
qbhit       0     0     0     0     0     0     0     1     1     1
tfl         1     1     1     1     0     0     0     0     0     1
ff          1     1     1     1     1     1     1     1     1     1
int         1     1     1     1     1     1     1     1     1     1
pd          1     1     1     1     1     1     1     1     1     1
fg          1     1     1     1     1     1     1     1     1     1

Box values, 2001-2008 anchors (next 4 games, same season). Chosen half-life 32 weeks (sum of MSE / MSE_replacement over groups, each at its best k):
  4: 8.4621, 8: 8.3128, 16: 8.2155, 32: 8.1871, 64: 8.1915, 128: 8.2020
group        n      k   skill       wmse  wmse_repl  k grid edge?
CB       11985     16   0.033   0.000875   0.000905
DL       20691      8   0.092   0.000719   0.000791
K         4079     16   0.134   0.000322   0.000371
LB       15241      8   0.075   0.000590   0.000637
QB        4468      4   0.297   0.015519   0.022091
RB       11168     16   0.022   0.008117   0.008302
S        10343     32   0.026   0.000548   0.000562
TE        5698     16   0.048   0.000598   0.000629
WR       12644     16   0.086   0.000674   0.000738

With/without ridge, 2006-2008 anchors (next 4 team-games, residual EPA/play, plays-weighted MSE; lambda 1e7 = box values only):
            lam  mse_off  mse_def  mse_icpt_off  mse_icpt_def      mse  mse_icpt
     125.000000 0.053462 0.053461      0.060498      0.049883 0.053462  0.055189
     250.000000 0.051279 0.050907      0.059279      0.049896 0.051093  0.054587
     500.000000 0.049977 0.049404      0.058512      0.049892 0.049691  0.054201
    1000.000000 0.049251 0.048587      0.058030      0.049877 0.048919  0.053952
    2000.000000 0.048889 0.048237      0.057721      0.049858 0.048563  0.053789
    4000.000000 0.048760 0.048203      0.057518      0.049844 0.048481  0.053680
    8000.000000 0.048782 0.048332      0.057382      0.049833 0.048557  0.053607
   16000.000000 0.048877 0.048493      0.057294      0.049827 0.048685  0.053560
   64000.000000 0.049055 0.048693      0.057211      0.049822 0.048874  0.053516
10000000.000000 0.049155 0.048782      0.057177      0.049820 0.048969  0.053498
Chosen lambda: 4000

Timing: prepare 5.2s, box grid 77.0s, ridge grid 20.1s, total 102.3s

Logged data/raw/ml/_train_all_runs/20261020T033823Z_m5_tune_players.json

M5 window REG 2012-2019 with moneylines: n = 2047, games hash 890722aef13c4355.
Training: B0 on REG 2001..S-1 (as M3); every other step on REG 2009..S-1 (seasons 2009-2011 for the 2012 model up to 2009-2018 for 2019). Team-games with a zero lineup delta in 2009-2019: 0.
Status probabilities (estimated on 2009-2015 rank-1 starters):
status  doubtful  none    out  practice  probable  questionable
group
CB         0.019   1.0  0.006       1.0       1.0         0.679
DL         0.030   1.0  0.000       1.0       1.0         0.778
K          0.018   1.0  0.001       1.0       1.0         0.763
LB         0.013   1.0  0.000       1.0       1.0         0.764
OL         0.023   1.0  0.002       1.0       1.0         0.765
QB         0.040   1.0  0.012       1.0       1.0         0.601
RB         0.006   1.0  0.000       1.0       1.0         0.868
S          0.005   1.0  0.000       1.0       1.0         0.727
TE         0.052   1.0  0.000       1.0       1.0         0.795
WR         0.048   1.0  0.000       1.0       1.0         0.813

B0 vs the saved M3 ladder A4s predictions on these games: max |diff| 0.00e+00

Ladder (n = 2047; diff = step minus B0 Brier, 95% paired bootstrap CI, 2,000 reps, seed 20261003; ECE p95 = one-sided null at this n):
step train        brier  logloss    acc    ece    p95  ok  vs B0 [95% CI]                1SE
B0   2001..S-1   0.2147   0.6195  0.650 0.0152 0.0330   y  +0.0000 [+0.0000, +0.0000]   yes *
B0r  2009..S-1   0.2150   0.6202  0.650 0.0146 0.0329   y  +0.0004 [-0.0000, +0.0007]
B1   2009..S-1   0.2149   0.6199  0.647 0.0185 0.0330   y  +0.0002 [-0.0006, +0.0011]   yes
B2   2009..S-1   0.2150   0.6202  0.650 0.0252 0.0334   y  +0.0004 [-0.0004, +0.0012]   yes
B3   2009..S-1   0.2154   0.6211  0.647 0.0239 0.0318   y  +0.0008 [-0.0004, +0.0019]
B4   2009..S-1   0.2154   0.6211  0.649 0.0210 0.0329   y  +0.0008 [-0.0004, +0.0020]
B5   2009..S-1   0.2155   0.6212  0.645 0.0263 0.0321   y  +0.0008 [-0.0003, +0.0020]
B3f  2009..S-1   0.2155   0.6212  0.647 0.0227 0.0321   y  +0.0008 [-0.0004, +0.0019]
Elo v2: 0.2175   Market (benchmark): 0.2110
Leak alarm (any step beating B0 by more than 0.006): none
Best candidate: B0; within one SE: ['B0', 'B1', 'B2']; chosen by the one-SE rule: B0.
M5 acceptance on the window (chosen beats B0 with CI excluding 0 and ECE check passing): FAIL

By split (Brier; diff = step minus B0 with 95% CI):
  weeks 1-4                      n   501  Elo 0.2251  B0 0.2264  B0r 0.2266 (+0.0002 [-0.0005, +0.0009])  B1 0.2273 (+0.0008 [-0.0013, +0.0030])  B2 0.2275 (+0.0011 [-0.0008, +0.0029])  B3 0.2273 (+0.0009 [-0.0013, +0.0031])  B3f 0.2273 (+0.0009 [-0.0013, +0.0031])
  weeks 5-9                      n   563  Elo 0.2120  B0 0.2100  B0r 0.2102 (+0.0003 [-0.0003, +0.0009])  B1 0.2109 (+0.0009 [-0.0006, +0.0025])  B2 0.2106 (+0.0006 [-0.0008, +0.0021])  B3 0.2108 (+0.0008 [-0.0013, +0.0029])  B3f 0.2107 (+0.0007 [-0.0014, +0.0028])
  weeks 10-18                    n   983  Elo 0.2167  B0 0.2114  B0r 0.2118 (+0.0005 [-0.0001, +0.0011])  B1 0.2109 (-0.0005 [-0.0017, +0.0007])  B2 0.2113 (-0.0001 [-0.0013, +0.0011])  B3 0.2120 (+0.0007 [-0.0011, +0.0025])  B3f 0.2122 (+0.0008 [-0.0010, +0.0026])
  2+ starters out (either team)  n   755  Elo 0.2161  B0 0.2144  B0r 0.2146 (+0.0002 [-0.0003, +0.0008])  B1 0.2139 (-0.0005 [-0.0019, +0.0009])  B2 0.2144 (-0.0000 [-0.0013, +0.0012])  B3 0.2145 (+0.0001 [-0.0017, +0.0020])  B3f 0.2145 (+0.0001 [-0.0018, +0.0020])
  fewer than 2 out               n  1292  Elo 0.2183  B0 0.2148  B0r 0.2153 (+0.0004 [-0.0001, +0.0009])  B1 0.2155 (+0.0007 [-0.0006, +0.0019])  B2 0.2155 (+0.0006 [-0.0005, +0.0017])  B3 0.2160 (+0.0011 [-0.0004, +0.0027])  B3f 0.2160 (+0.0012 [-0.0004, +0.0028])

Coefficients of B0 (last refit; range over the 8 refits):
  intercept                               +0.0482  [+0.0209, +0.0915]
  elo_logit                               +0.8415  [+0.6190, +0.8707]  per 1 SD (0.7456): +0.627
  adj_epa_margin                          +1.0869  [+0.8725, +2.2145]  per 1 SD (0.1299): +0.141
  qb_delta_diff                           +3.6071  [+2.8469, +3.7590]  per 1 SD (0.0621): +0.224
  sign check: all coefficients have the expected sign in every refit
  (B3 last refit: lineup_delta_diff +1.172 [-5.050, +3.380], preseason_change_diff -2.318 [-2.318, +8.618], preseason_change_diff_wk +4.869 [-5.464, +4.869])
  (B2 last refit: lineup_delta_diff +2.529 [+2.411, +4.232])
  (B1 last refit: lineup_delta_diff +4.117 [+3.329, +5.110])

Feature SDs on the window: lineup_delta_diff__box_full 0.0230, lineup_delta_diff__ww_full 0.0279, preseason_change_diff__ww_full 0.0509, qb_delta_diff 0.0621, adj_epa_margin 0.1299
Correlations: lineup_delta_diff__ww_full~qb_delta_diff +0.10, lineup_delta_diff__ww_full~elo_logit +0.03, preseason_change_diff__ww_full~elo_logit +0.13, lineup_delta_diff__box_full~lineup_delta_diff__ww_full +0.89

Timing: load_s 6.4s, m3_frame_s 3.2s, credit_lineups_s 15.0s, values_s 21.5s, features_s 15.7s, ladder_s 1.7s, total_s 63.8s

8 runs written to data/raw/ml/_train_all_runs/

[6. M5 box-score player values: 167s]

**Retrained vs the committed development record**: 9 of 9 runs match (tolerance max(5e-05, 0.2% of the record) on every metric).

No holdout result exists for M5 by design: nothing beat A4s on the development window.

## 7. M5b: on-field player ratings (RAPM)

Bayesian plus-minus ratings from all 22 players on every play (participation data, 2016+, CC BY-SA), tested
season-ahead against team ratings and box-score values. **Failed** on the holdout: it beats team ratings but loses
to box-score values summed over the on-field players, so it is kept as a descriptive player view only.

In [10]:
with section("7. M5b RAPM"):
    recs_m5b = run_main("ml_m5b", ["clean"])
    if FULL:
        recs_m5b += run_main("ml_m5b", ["tune"])
    recs_m5b += run_main("ml_m5b", ["dev"])
match_table(recs_m5b)
locked_holdout(["m5b_"])

Participation cleaning (kept = exactly 11 + 11 distinct GSIS IDs after the side repair):
 season era  clean_plays  joined  raw_11_11  kept  repaired  raw_drop_rate  drop_rate  games
   2016 ngs        28488   28488      24856 28367      3511         0.1275     0.0042    267
   2017 ngs        28086   28084      28051 28051         0         0.0012     0.0012    267
   2018 ngs        27629   27629      25442 27611      2169         0.0792     0.0007    267
   2019 ngs        27957   27957      26597 27932      1335         0.0486     0.0009    267
   2020 ngs        28744   28744      28715 28715         0         0.0010     0.0010    269
   2021 ngs        29557   29557      29535 29535         0         0.0007     0.0007    285
   2022 ngs        30439   30439      30412 30412         0         0.0009     0.0009    284
   2023 ftn        30065   30065      30040 30040         0         0.0008     0.0008    285
   2024 ftn        29513   29513      29489 29489         0         0.0008     0.0008    285
   2025 ftn        29391   29391      29354 29354         0         0.0013     0.0013    285

Distinct players on the field per season:
 season era  players
   2016 ngs     1833
   2017 ngs     1851
   2018 ngs     1839
   2019 ngs     1858
   2020 ngs     1964
   2021 ngs     2034
   2022 ngs     1996
   2023 ftn     1905
   2024 ftn     1969
   2025 ftn     1936

Players per season and position group (group from that season's depth charts, then rosters):
group    CB   DL   K   LB   OL  QB   RB    S   TE   WR  unknown
season
2016    203  284  11  263  304  64  169  162  129  212       32
2017    195  301   5  269  305  65  163  164  128  218       38
2018    200  302   8  252  303  65  160  163  132  225       29
2019    211  296   8  264  296  66  157  171  130  236       23
2020    224  331   6  264  313  74  169  169  140  244       30
2021    230  338   7  291  335  72  167  167  143  260       24
2022    237  339   5  271  327  78  164  161  137  248       29
2023    226  320   5  269  313  76  148  159  138  232       19
2024    224  338   3  283  329  73  147  158  136  246       32
2025    225  331   5  280  320  72  150  157  139  244       13

By source era (distinct players):
group   CB   DL   K   LB   OL   QB   RB    S   TE   WR  unknown
era
ftn    351  480  12  423  462  107  231  233  198  353       46
ngs    533  712  30  692  648  151  400  387  317  570       86

On-field player-snaps per kept play (must be 22): 2016 22.00, 2017 22.00, 2018 22.00, 2019 22.00, 2020 22.00, 2021 22.00, 2022 22.00, 2023 22.00, 2024 22.00, 2025 22.00

Start {'lam': {'CB': 4000.0, 'DL': 4000.0, 'LB': 4000.0, 'OL': 4000.0, 'QB': 4000.0, 'RB': 4000.0, 'S': 4000.0, 'TE': 4000.0, 'WR': 4000.0}, 'lam_other': 20000.0, 'decay': 0.5, 'situation': True, 'box_scale': 1.0}: MSE 1.940818

Sweep 1: MSE 1.938726  decay 1.0  box_scale 0.25  situation True  CB 1024000 DL 1024000 LB 2000 OL 2000 QB 250 RB 1000 S 4000 TE 4000 WR 8000

Sweep 2: MSE 1.938630  decay 1.0  box_scale 0.25  situation True  CB 32000 DL 1024000 LB 2000 OL 1000 QB 500 RB 1000 S 4000 TE 2000 WR 4000

Sweep 3: MSE 1.938630  decay 1.0  box_scale 0.25  situation True  CB 32000 DL 1024000 LB 2000 OL 1000 QB 500 RB 1000 S 4000 TE 2000 WR 4000

Chosen: {'lam': {'CB': 32000.0, 'DL': 1024000.0, 'LB': 2000.0, 'OL': 1000.0, 'QB': 500.0, 'RB': 1000.0, 'S': 4000.0, 'TE': 2000.0, 'WR': 4000.0}, 'lam_other': 20000.0, 'decay': 1.0, 'situation': True, 'box_scale': 0.25}  dev MSE 1.938630
Situation terms on; the other choice scores 1.945181 (+0.006551).
Ridge strengths at a grid edge: ['DL', 'decay']
Diagnostics: box_scale_0.0 1.938815 (+0.000184), box_scale_1.0 1.939498 (+0.000868), all_lam_equal_best 1.939660 (+0.001030)
362 settings scored; timing: load 8s, tuning 42s
M5b dev evaluation, frozen settings: {'lam': {'CB': 32000.0, 'DL': 1024000.0, 'LB': 2000.0, 'OL': 1000.0, 'QB': 500.0, 'RB': 1000.0, 'S': 4000.0, 'TE': 2000.0, 'WR': 4000.0}, 'lam_other': 20000.0, 'decay': 1.0, 'situation': True, 'box_scale': 0.25}

Season-ahead play-level EPA MSE (dev): 55,543 plays in 534 games (seasons [2018, 2019])
  model           MSE   RAPM minus model, 95% game-cluster CI
  rapm        1.93863
  team        1.94136   -0.00273 [-0.00417, -0.00128]
  box         1.94050   -0.00187 [-0.00319, -0.00048]
  intercept   1.94914   -0.01051 [-0.01352, -0.00734]
  (team_vs_intercept: -0.00778 [-0.01081, -0.00478])
  (box_vs_intercept: -0.00864 [-0.01152, -0.00587])
  (box_vs_team: -0.00086 [-0.00238, +0.00075])
  2018: rapm 1.92938  team 1.93158  box 1.93194  intercept 1.94384  | RAPM-team -0.00219 [-0.00399, -0.00039]  RAPM-box -0.00256 [-0.00443, -0.00079]
  2019: rapm 1.94777  team 1.95103  box 1.94896  intercept 1.95438  | RAPM-team -0.00326 [-0.00550, -0.00112]  RAPM-box -0.00119 [-0.00316, +0.00076]
  Team-game EPA margin MSE (534 games): rapm 0.17934  team 0.18629  box 0.18900  intercept 0.19298
    RAPM minus team -0.0069 [-0.0120, -0.0019]; minus box -0.0097 [-0.0152, -0.0046]; minus intercept -0.0136 [-0.0215, -0.0060]

Game model (descriptive): REG games with moneylines, n = 512 (hash 37d2396968649d9f)
  A4s 0.2170; A4s + rapm_lineup_delta_diff 0.2177; diff +0.0007 [-0.0012, +0.0025]; coefficient by season 2018 -4.47, 2019 -1.15; feature SD 0.0345; corr with market minus A4s +0.20

Year-to-year correlation of player values (both seasons >= 200 snaps; n in parentheses):
  chained fits:
    CB  2016->2017 +0.69 (92)  2017->2018 +0.73 (90)  2018->2019 +0.65 (89)
    DL  2016->2017 +0.40 (130)  2017->2018 +0.65 (133)  2018->2019 +0.83 (128)
    LB  2016->2017 +0.79 (98)  2017->2018 +0.85 (98)  2018->2019 +0.76 (98)
    OL  2016->2017 +0.63 (161)  2017->2018 +0.81 (161)  2018->2019 +0.88 (150)
    QB  2016->2017 +0.84 (30)  2017->2018 +0.90 (27)  2018->2019 +0.80 (26)
    RB  2016->2017 +0.81 (32)  2017->2018 +0.87 (37)  2018->2019 +0.88 (46)
    S   2016->2017 +0.71 (69)  2017->2018 +0.87 (70)  2018->2019 +0.76 (72)
    TE  2016->2017 +0.68 (48)  2017->2018 +0.85 (48)  2018->2019 +0.79 (45)
    WR  2016->2017 +0.64 (91)  2017->2018 +0.83 (89)  2018->2019 +0.85 (89)
    rating minus prior: CB +0.70/+0.61/+0.61; DL +0.16/+0.22/+0.19; LB +0.79/+0.86/+0.77; OL +0.63/+0.81/+0.88; QB +0.83/+0.88/+0.82; RB +0.82/+0.88/+0.88; S +0.71/+0.88/+0.76; TE +0.66/+0.84/+0.81; WR +0.66/+0.84/+0.85
  single-season fits:
    CB  2016->2017 +0.46 (92)  2017->2018 +0.49 (90)  2018->2019 +0.39 (89)
    DL  2016->2017 +0.40 (130)  2017->2018 +0.65 (133)  2018->2019 +0.89 (128)
    LB  2016->2017 +0.28 (98)  2017->2018 +0.26 (98)  2018->2019 +0.18 (98)
    OL  2016->2017 +0.06 (161)  2017->2018 +0.11 (161)  2018->2019 +0.15 (150)
    QB  2016->2017 +0.42 (30)  2017->2018 +0.59 (27)  2018->2019 +0.29 (26)
    RB  2016->2017 +0.46 (32)  2017->2018 +0.41 (37)  2018->2019 +0.34 (46)
    S   2016->2017 +0.14 (69)  2017->2018 +0.21 (70)  2018->2019 +0.23 (72)
    TE  2016->2017 -0.09 (48)  2017->2018 +0.19 (48)  2018->2019 +0.17 (45)
    WR  2016->2017 +0.22 (91)  2017->2018 +0.35 (89)  2018->2019 +0.39 (89)
    rating minus prior: CB +0.03/-0.02/-0.01; DL -0.06/+0.12/+0.14; LB +0.24/+0.26/+0.12; OL +0.06/+0.11/+0.15; QB +0.11/+0.26/-0.09; RB +0.45/+0.35/+0.27; S +0.12/+0.19/+0.20; TE -0.25/+0.10/+0.12; WR +0.01/+0.09/+0.16

Sanity: ratings fit through 2019 (value = EPA per play on the field, + is good for his team), players with >= 300 snaps in 2019:
  QB (n 34) top 10: Patrick Mahomes KC +0.131±0.045 (849); Jimmy Garoppolo SF +0.110±0.042 (989); Deshaun Watson HOU +0.095±0.045 (937); Aaron Rodgers GB +0.084±0.044 (925); Derek Carr LV +0.070±0.046 (813); Dak Prescott DAL +0.069±0.049 (848); Matt Ryan ATL +0.065±0.049 (819); Drew Brees NO +0.065±0.045 (561); Lamar Jackson BAL +0.060±0.048 (796); Baker Mayfield CLE +0.057±0.047 (809)
  QB bottom 5: Mason Rudolph PIT -0.043±0.050 (451); Jared Goff LA -0.019±0.046 (845); Dwayne Haskins WAS -0.015±0.051 (359); Daniel Jones NYG -0.014±0.050 (659); Joe Flacco DEN -0.009±0.040 (435)
  RB (n 40) top 10: Derrick Henry TEN +0.073±0.033 (592); Aaron Jones GB +0.054±0.035 (611); Leonard Fournette JAX +0.050±0.034 (688); Alvin Kamara NO +0.045±0.034 (531); Austin Ekeler LAC +0.041±0.035 (507); Devin Singletary BUF +0.038±0.039 (522); Kyle Juszczyk SF +0.037±0.031 (391); Raheem Mostert SF +0.033±0.038 (362); Adrian Peterson WAS +0.032±0.034 (351); James White NE +0.030±0.032 (389)
  RB bottom 5: Carlos Hyde HOU -0.040±0.031 (507); Devonta Freeman ATL -0.028±0.033 (543); David Montgomery CHI -0.023±0.038 (497); Latavius Murray NO -0.018±0.031 (351); David Johnson ARI -0.017±0.034 (352)
  WR (n 103) top 10: Tyreek Hill KC +0.032±0.020 (618); Robert Woods LA +0.028±0.020 (762); Alshon Jeffery PHI +0.025±0.019 (393); Cooper Kupp LA +0.024±0.020 (676); Julio Jones ATL +0.023±0.020 (621); Emmanuel Sanders SF +0.021±0.019 (849); Sammy Watkins KC +0.020±0.019 (752); David Moore SEA +0.019±0.020 (312); Tyler Lockett SEA +0.018±0.020 (894); Chris Godwin Jr. TB +0.018±0.020 (782)
  WR bottom 5: Josh Reynolds LA -0.010±0.020 (362); Auden Tate CIN -0.007±0.021 (478); Alex Erickson CIN -0.006±0.020 (459); DaeSean Hamilton DEN -0.006±0.021 (490); DeVante Parker MIA -0.005±0.020 (642)
  TE (n 53) top 10: Mark Andrews BAL +0.030±0.028 (353); Jeff Heuerman DEN +0.028±0.026 (324); Travis Kelce KC +0.028±0.028 (930); Darren Fells HOU +0.027±0.025 (720); Jason Witten DAL +0.022±0.028 (686); Dallas Goedert PHI +0.021±0.026 (688); Tyler Higbee LA +0.019±0.026 (516); Nick Boyle BAL +0.017±0.026 (612); MyCole Pruitt TEN +0.017±0.028 (423); Jimmy Graham GB +0.017±0.025 (527)
  TE bottom 5: Durham Smythe MIA -0.032±0.028 (373); Nick Vannett PIT -0.017±0.026 (371); Benjamin Watson NE -0.015±0.026 (381); Matt LaCosse NE -0.015±0.027 (373); Josh Hill NO -0.012±0.025 (529)
  OL (n 187) top 10: Andrew Whitworth LA +0.051±0.035 (846); Nick Easton NO +0.041±0.033 (324); Justin Pugh ARI +0.039±0.033 (840); Nate Solder NYG +0.039±0.032 (810); Bradley Bozeman BAL +0.037±0.037 (855); Alex Cappa TB +0.036±0.037 (748); Tyron Smith DAL +0.036±0.034 (675); Joe Dahl DET +0.034±0.036 (690); Dan Feeney LAC +0.034±0.037 (848); Lane Johnson PHI +0.030±0.033 (613)
  OL bottom 5: Ereck Flowers WAS -0.067±0.033 (720); Billy Price CIN -0.038±0.036 (401); Alex Lewis NYJ -0.037±0.032 (529); Isaac Seumalo PHI -0.034±0.032 (1031); Will Richardson JAX -0.034±0.039 (331)
  DL (n 144) top 10: Danielle Hunter MIN +0.010±0.001 (817); Aaron Donald LA +0.009±0.001 (722); DeMarcus Lawrence DAL +0.009±0.001 (522); Robert Quinn DAL +0.007±0.001 (498); Maxx Crosby LV +0.007±0.001 (581); Frank Clark KC +0.007±0.001 (685); Yannick Ngakoue JAX +0.006±0.001 (585); Vic Beasley ATL +0.006±0.001 (582); Trent Murphy BUF +0.006±0.001 (609); Jerry Hughes BUF +0.006±0.001 (594)
  DL bottom 5: Leonard Williams NYG -0.003±0.001 (560); DaQuan Jones TEN -0.003±0.001 (651); DJ Reader HOU -0.002±0.001 (595); Kyle Phillips NYJ -0.002±0.001 (349); Davon Godchaux MIA -0.002±0.001 (538)
  LB (n 115) top 10: Matthew Judon BAL +0.052±0.024 (599); Eric Kendricks MIN +0.043±0.025 (877); Khalil Mack CHI +0.041±0.024 (715); Fred Warner SF +0.037±0.025 (946); Za'Darius Smith GB +0.032±0.024 (782); Jamie Collins NE +0.032±0.023 (643); Roquan Smith CHI +0.031±0.027 (603); Dante Fowler Jr. LA +0.031±0.024 (696); Anthony Barr MIN +0.030±0.025 (881); Matt Milano BUF +0.030±0.026 (816)
  LB bottom 5: Oshane Ximines NYG -0.036±0.028 (409); Preston Brown CIN -0.032±0.023 (340); Nicholas Morrow LV -0.032±0.026 (567); Tahir Whitehead LV -0.025±0.022 (727); Tarell Basham NYJ -0.024±0.027 (390)
  CB (n 103) top 10: Marcus Peters BAL +0.006±0.007 (811); Kyle Fuller CHI +0.004±0.008 (828); Stephon Gilmore NE +0.004±0.007 (758); Tre'Davious White BUF +0.004±0.008 (858); Sean Murphy-Bunting TB +0.004±0.008 (576); Marshon Lattimore NO +0.004±0.008 (661); Richard Sherman SF +0.004±0.007 (867); Jamel Dean TB +0.004±0.008 (318); Jimmy Smith BAL +0.003±0.008 (307); Jalen Ramsey LA +0.003±0.008 (544)
  CB bottom 5: B.W. Webb CIN -0.005±0.008 (657); Tramaine Brock ARI -0.004±0.007 (776); Byron Jones DAL -0.003±0.008 (663); T.J. Carrie CLE -0.002±0.008 (505); Greedy Williams CLE -0.002±0.008 (514)
  S (n 77) top 10: Harrison Smith MIN +0.028±0.020 (891); Kareem Jackson DEN +0.023±0.019 (676); Tyrann Mathieu KC +0.022±0.018 (1002); Earl Thomas BAL +0.021±0.019 (700); Eddie Jackson CHI +0.018±0.020 (828); Kevin Byard TEN +0.018±0.019 (1058); Chuck Clark BAL +0.015±0.020 (579); Rodney McLeod Jr. PHI +0.015±0.019 (877); Minkah Fitzpatrick PIT +0.013±0.019 (846); Terrell Edmunds PIT +0.012±0.020 (857)
  S bottom 5: Eric Reid CAR -0.016±0.019 (772); Jessie Bates CIN -0.016±0.020 (818); Antoine Bethea NYG -0.016±0.018 (913); Roderic Teamer LAC -0.008±0.021 (304); Bobby McCain MIA -0.007±0.019 (413)

How far ratings moved from their priors (players above), by group:
group   n  mean_abs_move  sd_value  sd_prior  median_sd  prior_sd  sd_ratio
   CB 103         0.0012    0.0020    0.0013     0.0075    0.0077    0.9859
   DL 144         0.0000    0.0027    0.0027     0.0014    0.0014    0.9995
   LB 115         0.0145    0.0176    0.0031     0.0249    0.0306    0.8124
   OL 187         0.0149    0.0185    0.0000     0.0354    0.0433    0.8177
   QB  34         0.0290    0.0374    0.0144     0.0453    0.0612    0.7400
   RB  40         0.0198    0.0248    0.0037     0.0341    0.0433    0.7873
    S  77         0.0075    0.0089    0.0007     0.0194    0.0216    0.8942
   TE  53         0.0100    0.0129    0.0021     0.0264    0.0306    0.8636
   WR 103         0.0055    0.0080    0.0029     0.0201    0.0216    0.9269

Timing: load_s 8s, evaluate_s 29s, game_model_s 6s, y2y_s 5s, sanity_s 1s

Runs written to data/raw/ml/_train_all_runs/ (label m5bdev)

[7. M5b RAPM: 103s]

**Retrained vs the committed development record**: 6 of 6 runs match (tolerance max(5e-05, 0.2% of the record) on every metric).

**Locked 2020-2025 holdout, loaded from `experiments/runs/` (not recomputed)**

## 8. M6: play outcome model

Predicts the whole yards-gained distribution of a play from pre-snap facts (down, distance, field position,
personnel, formation, team ratings). A gradient-boosted model and three small neural nets compete against a plain
situational baseline, scored by CRPS (lower is better). **Passed** on the holdout (CRPS about 0.018 better than the
baseline, in every season). Neural-net training is the slow part and is not bit-for-bit reproducible, so small
differences from the record are expected.

In [11]:
with section("8. M6 play model"):
    recs_m6 = run_main("ml_m6", ["fields"])
    recs_m6 += run_main("ml_m6", ["dev"])
match_table(recs_m6)
locked_holdout(["m6_"])

 season era  plays  raw_formations  form_missing  shotgun  pistol  under_center  other  box_missing  box_mean  box_sd  box_8plus  pers_missing    rb    te    wr    ol   p11    dl    lb    db  nickel_or_more
   2016 ngs  28367               7         0.009    0.592   0.040         0.355  0.005        0.001     6.371   1.059      0.124           0.0 1.100 1.237 2.606 5.055 0.587 3.201 3.009 4.786           0.688
   2017 ngs  28051               7         0.008    0.570   0.016         0.403  0.004        0.001     6.492   1.081      0.158           0.0 1.122 1.305 2.527 5.037 0.578 3.245 2.980 4.772           0.653
   2018 ngs  27611               7         0.009    0.607   0.020         0.362  0.002        0.001     6.374   1.050      0.121           0.0 1.108 1.260 2.584 5.031 0.621 3.412 2.706 4.880           0.740
   2019 ngs  27932               7         0.001    0.604   0.032         0.360  0.003        0.001     6.341   1.048      0.114           0.0 1.120 1.278 2.547 5.043 0.571 3.149 2.991 4.854           0.711
   2020 ngs  28715               7         0.004    0.623   0.032         0.338  0.003        0.001     6.347   1.036      0.115           0.0 1.106 1.290 2.567 5.024 0.576 3.407 2.713 4.878           0.747
   2021 ngs  29535               7         0.007    0.620   0.030         0.339  0.004        0.001     6.363   1.032      0.123           0.0 1.101 1.299 2.555 5.038 0.583 3.216 2.912 4.869           0.751
   2022 ngs  30412               7         0.001    0.629   0.045         0.318  0.007        0.001     6.370   1.014      0.121           0.0 1.116 1.305 2.547 5.029 0.611 3.166 2.999 4.833           0.737
   2023 ftn  30040               3         0.003    0.681   0.041         0.275  0.000        0.002     6.271   1.087      0.102           0.0 1.089 1.279 2.594 5.026 0.621 3.168 2.938 4.892           0.782
   2024 ftn  29489               3         0.001    0.614   0.096         0.289  0.000        0.001     6.103   0.930      0.051           0.0 1.080 1.327 2.561 5.029 0.612 3.230 2.917 4.848           0.763
   2025 ftn  29354               3         0.002    0.608   0.049         0.341  0.000        0.002     6.231   0.841      0.055           0.0 1.097 1.363 2.476 5.054 0.564 3.075 3.147 4.772           0.696
M6 dev evaluation, season-ahead 2018-2019 (training from 2016)

Inputs loaded in 26s: 111,961 plays 2016-2019

  situation 2018: 27,611 plays, 50s baseline 4.0540 gbm 4.0330 N0 4.0347 N1 4.0374 N2 4.0373

  situation 2019: 27,932 plays, 126s baseline 3.9953 gbm 3.9792 N0 3.9840 N1 3.9822 N2 3.9827

  call 2018: 27,611 plays, 70s baseline 3.9747 gbm 3.9574 N0 3.9572 N1 3.9578 N2 3.9562

  call 2019: 27,932 plays, 110s baseline 3.9223 gbm 3.9038 N0 3.9078 N1 3.9044 N2 3.9043

== situation view: 55,543 plays, 534 games (games 2e7aa347318c6509) ==
model        CRPS  logloss  tovBrier  CRPS vs baseline [95% CI]      1SE  ECE first (p95)  ECE 20+  ECE loss ECE tov
baseline   4.0245   2.9731   0.01991                                      0.0061! (0.0056)  0.0060!  0.0004   0.0007
gbm        4.0059   2.9442   0.01984  -0.0185 [-0.0217, -0.0155]     yes *0.0052 (0.0057)  0.0033!  0.0012   0.0004
N0         4.0092   2.9454   0.01987  -0.0152 [-0.0188, -0.0117]          0.0053 (0.0058)  0.0056!  0.0039!  0.0018!
N1         4.0096   2.9445   0.01986  -0.0148 [-0.0187, -0.0110]          0.0052 (0.0059)  0.0061!  0.0038!  0.0010
N2         4.0098   2.9445   0.01986  -0.0146 [-0.0185, -0.0106]          0.0051 (0.0056)  0.0046!  0.0040!  0.0012!
one-SE: best gbm, within ['gbm'], chosen gbm  (! = ECE above the one-sided null p95, descriptive; X = fails the rule: above both p95 and 0.01)
log loss vs baseline: gbm -0.0289 [-0.0315, -0.0263]; N0 -0.0278 [-0.0306, -0.0248]; N1 -0.0286 [-0.0315, -0.0257]; N2 -0.0286 [-0.0315, -0.0257]
turnover Brier vs baseline: gbm -0.00007 [-0.00011, -0.00004]; N0 -0.00004 [-0.00007, -0.00002]; N1 -0.00005 [-0.00008, -0.00002]; N2 -0.00005 [-0.00008, -0.00002]
between models (CRPS a - b): gbm-N0 -0.0033 [-0.0055, -0.0011]; N1-N0 +0.0004 [-0.0009, +0.0018]; N2-N0 +0.0006 [-0.0008, +0.0021]; N2-N1 +0.0002 [-0.0012, +0.0017]; gbm-N1 -0.0037 [-0.0060, -0.0013]; gbm-N2 -0.0039 [-0.0063, -0.0015]
  2018: baseline 4.0540; gbm 4.0330 (-0.0211 [-0.0257, -0.0165]); N0 4.0347 (-0.0193 [-0.0244, -0.0144]); N1 4.0374 (-0.0166 [-0.0225, -0.0109]); N2 4.0373 (-0.0167 [-0.0221, -0.0115])
  2019: baseline 3.9953; gbm 3.9792 (-0.0160 [-0.0203, -0.0119]); N0 3.9840 (-0.0112 [-0.0160, -0.0064]); N1 3.9822 (-0.0131 [-0.0179, -0.0082]); N2 3.9827 (-0.0125 [-0.0178, -0.0073])
splits (CRPS; model minus baseline [95% CI]):
  run         21,113  base 2.7958  gbm -0.0083 [-0.0120, -0.0044]  N0 -0.0178 [-0.0225, -0.0135]  N1 -0.0198 [-0.0248, -0.0149]  N2 -0.0160 [-0.0208, -0.0112]
  pass        34,430  base 4.7779  gbm -0.0248 [-0.0297, -0.0201]  N0 -0.0137 [-0.0189, -0.0082]  N1 -0.0118 [-0.0174, -0.0063]  N2 -0.0137 [-0.0195, -0.0080]
  down1       25,063  base 3.9360  gbm -0.0180 [-0.0223, -0.0139]  N0 -0.0133 [-0.0183, -0.0086]  N1 -0.0113 [-0.0166, -0.0060]  N2 -0.0133 [-0.0186, -0.0083]
  down2       18,547  base 3.8998  gbm -0.0221 [-0.0280, -0.0167]  N0 -0.0184 [-0.0250, -0.0118]  N1 -0.0186 [-0.0255, -0.0121]  N2 -0.0170 [-0.0240, -0.0101]
  down3       11,190  base 4.4588  gbm -0.0145 [-0.0207, -0.0078]  N0 -0.0156 [-0.0243, -0.0068]  N1 -0.0169 [-0.0260, -0.0076]  N2 -0.0136 [-0.0226, -0.0043]
  down4          743  base 3.5808  gbm -0.0092 [-0.0494, +0.0298]  N0 +0.0036 [-0.0348, +0.0424]  N1 -0.0088 [-0.0550, +0.0360]  N2 -0.0143 [-0.0619, +0.0317]
  zone_1_20    7,951  base 2.3443  gbm -0.0242 [-0.0307, -0.0176]  N0 -0.0186 [-0.0256, -0.0111]  N1 -0.0181 [-0.0254, -0.0104]  N2 -0.0200 [-0.0275, -0.0128]
  zone_21_50  16,376  base 4.2007  gbm -0.0157 [-0.0210, -0.0099]  N0 -0.0089 [-0.0150, -0.0029]  N1 -0.0108 [-0.0171, -0.0045]  N2 -0.0100 [-0.0164, -0.0034]
  zone_51_80  26,211  base 4.3935  gbm -0.0178 [-0.0228, -0.0134]  N0 -0.0159 [-0.0214, -0.0109]  N1 -0.0144 [-0.0203, -0.0088]  N2 -0.0138 [-0.0199, -0.0080]
  zone_81_99   5,005  base 4.1845  gbm -0.0227 [-0.0337, -0.0124]  N0 -0.0270 [-0.0414, -0.0134]  N1 -0.0253 [-0.0400, -0.0112]  N2 -0.0252 [-0.0404, -0.0105]
  era_ngs     55,543  base 4.0245  gbm -0.0185 [-0.0217, -0.0155]  N0 -0.0152 [-0.0188, -0.0117]  N1 -0.0148 [-0.0187, -0.0110]  N2 -0.0146 [-0.0185, -0.0106]
Acceptance rule on this window (chosen beats baseline, CI upper < 0, P(first) ECE <= null p95 or 0.01): PASS

== call view: 55,543 plays, 534 games (games 2e7aa347318c6509) ==
model        CRPS  logloss  tovBrier  CRPS vs baseline [95% CI]      1SE  ECE first (p95)  ECE 20+  ECE loss ECE tov
baseline   3.9484   2.8710   0.01983                                      0.0046 (0.0057)  0.0059!  0.0072!  0.0006
gbm        3.9304   2.8528   0.01976  -0.0180 [-0.0208, -0.0152]     yes *0.0058! (0.0056)  0.0032!  0.0036!  0.0005
N0         3.9324   2.8513   0.01981  -0.0160 [-0.0195, -0.0125]          0.0060! (0.0056)  0.0041!  0.0043!  0.0009
N1         3.9310   2.8492   0.01980  -0.0174 [-0.0213, -0.0139]          0.0053 (0.0056)  0.0034!  0.0039!  0.0000
N2         3.9301   2.8493   0.01980  -0.0183 [-0.0224, -0.0145]     yes  0.0042 (0.0056)  0.0026!  0.0032!  0.0003
one-SE: best N2, within ['gbm', 'N2'], chosen gbm  (! = ECE above the one-sided null p95, descriptive; X = fails the rule: above both p95 and 0.01)
log loss vs baseline: gbm -0.0182 [-0.0208, -0.0154]; N0 -0.0196 [-0.0223, -0.0170]; N1 -0.0218 [-0.0246, -0.0191]; N2 -0.0217 [-0.0245, -0.0189]
turnover Brier vs baseline: gbm -0.00006 [-0.00010, -0.00003]; N0 -0.00002 [-0.00004, -0.00000]; N1 -0.00003 [-0.00005, -0.00001]; N2 -0.00003 [-0.00005, -0.00000]
between models (CRPS a - b): gbm-N0 -0.0020 [-0.0046, +0.0007]; N1-N0 -0.0014 [-0.0030, +0.0002]; N2-N0 -0.0023 [-0.0040, -0.0004]; N2-N1 -0.0009 [-0.0022, +0.0004]; gbm-N1 -0.0006 [-0.0031, +0.0021]; gbm-N2 +0.0003 [-0.0027, +0.0033]
  2018: baseline 3.9747; gbm 3.9574 (-0.0173 [-0.0213, -0.0135]); N0 3.9572 (-0.0174 [-0.0222, -0.0126]); N1 3.9578 (-0.0169 [-0.0217, -0.0121]); N2 3.9562 (-0.0185 [-0.0231, -0.0137])
  2019: baseline 3.9223; gbm 3.9038 (-0.0186 [-0.0227, -0.0143]); N0 3.9078 (-0.0146 [-0.0198, -0.0092]); N1 3.9044 (-0.0179 [-0.0234, -0.0121]); N2 3.9043 (-0.0181 [-0.0240, -0.0119])
splits (CRPS; model minus baseline [95% CI]):
  run         21,113  base 2.7086  gbm -0.0147 [-0.0182, -0.0111]  N0 -0.0089 [-0.0127, -0.0051]  N1 -0.0110 [-0.0150, -0.0071]  N2 -0.0112 [-0.0153, -0.0070]
  pass        34,430  base 4.7086  gbm -0.0200 [-0.0240, -0.0160]  N0 -0.0203 [-0.0254, -0.0154]  N1 -0.0213 [-0.0268, -0.0160]  N2 -0.0226 [-0.0285, -0.0169]
  down1       25,063  base 3.8333  gbm -0.0162 [-0.0205, -0.0124]  N0 -0.0177 [-0.0231, -0.0127]  N1 -0.0181 [-0.0233, -0.0126]  N2 -0.0205 [-0.0259, -0.0150]
  down2       18,547  base 3.8301  gbm -0.0219 [-0.0273, -0.0167]  N0 -0.0147 [-0.0214, -0.0085]  N1 -0.0166 [-0.0237, -0.0101]  N2 -0.0164 [-0.0238, -0.0094]
  down3       11,190  base 4.4332  gbm -0.0163 [-0.0235, -0.0086]  N0 -0.0147 [-0.0232, -0.0060]  N1 -0.0182 [-0.0270, -0.0094]  N2 -0.0165 [-0.0266, -0.0067]
  down4          743  base 3.4791  gbm -0.0016 [-0.0328, +0.0302]  N0 -0.0095 [-0.0411, +0.0220]  N1 -0.0018 [-0.0343, +0.0315]  N2 -0.0180 [-0.0514, +0.0140]
  zone_1_20    7,951  base 2.3132  gbm -0.0199 [-0.0272, -0.0127]  N0 -0.0135 [-0.0210, -0.0061]  N1 -0.0130 [-0.0202, -0.0057]  N2 -0.0129 [-0.0207, -0.0052]
  zone_21_50  16,376  base 4.1236  gbm -0.0169 [-0.0226, -0.0113]  N0 -0.0117 [-0.0180, -0.0054]  N1 -0.0131 [-0.0194, -0.0068]  N2 -0.0158 [-0.0220, -0.0096]
  zone_51_80  26,211  base 4.3052  gbm -0.0167 [-0.0210, -0.0127]  N0 -0.0177 [-0.0227, -0.0125]  N1 -0.0196 [-0.0250, -0.0141]  N2 -0.0202 [-0.0260, -0.0143]
  zone_81_99   5,005  base 4.1037  gbm -0.0244 [-0.0339, -0.0141]  N0 -0.0249 [-0.0400, -0.0093]  N1 -0.0265 [-0.0418, -0.0106]  N2 -0.0250 [-0.0401, -0.0084]
  era_ngs     55,543  base 3.9484  gbm -0.0180 [-0.0208, -0.0152]  N0 -0.0160 [-0.0195, -0.0125]  N1 -0.0174 [-0.0213, -0.0139]  N2 -0.0183 [-0.0224, -0.0145]
Acceptance rule on this window (chosen beats baseline, CI upper < 0, P(first) ECE <= null p95 or 0.01): PASS
N1 embedding norm vs training snaps (situation_2018): spearman -0.63; <100: 0.160 (n 945), 100-299: 0.097 (n 432), 300-999: 0.071 (n 758), 1000-2999: 0.046 (n 484), 3000+: nan (n 0)
N1 embedding norm vs training snaps (situation_2019): spearman -0.77; <100: 0.016 (n 1130), 100-299: 0.005 (n 484), 300-999: 0.004 (n 753), 1000-2999: 0.003 (n 744), 3000+: 0.003 (n 1)
N1 embedding norm vs training snaps (call_2018): spearman -0.52; <100: 0.091 (n 945), 100-299: 0.060 (n 432), 300-999: 0.048 (n 758), 1000-2999: 0.038 (n 484), 3000+: nan (n 0)
N1 embedding norm vs training snaps (call_2019): spearman -0.71; <100: 0.036 (n 1130), 100-299: 0.008 (n 484), 300-999: 0.006 (n 753), 1000-2999: 0.004 (n 744), 3000+: 0.004 (n 1)

Timing: {"load_s": 25.5, "scoring_s": 24.4} | per view-season: situation_2018 50s, situation_2019 126s, call_2018 70s, call_2019 110s

Runs written to data/raw/ml/_train_all_runs/ (label m6dev)

[8. M6 play model: 408s]

**Retrained vs the committed development record**: 10 of 10 runs match (tolerance max(5e-05, 0.2% of the record) on every metric).

**Locked 2020-2025 holdout, loaded from `experiments/runs/` (not recomputed)**

## 9. M7a: win probability and fourth-down decisions

Our own win-probability model (no betting inputs), plus field-goal, punt and fourth-down conversion models that
value going for it, kicking and punting. The win-probability model **passed** (Brier 0.1559 vs nflfastR's 0.1659).
The original conversion engine **failed** its calibration bar; the revised engine (v2) is evaluated on development
seasons below; its real test is the 2026 season, which cannot be read before 2027. This notebook only retrains and
scores on development seasons.

In [12]:
BOOT = 50 if FULL else 4               # bootstrap refits per season for the uncertainty bands (the record used 50)
with section("9. M7a win prob + fourth down"):
    recs_m7a = run_main("ml_m7a", ["dev", "--boot", str(BOOT)])
    recs_m7a += run_main("ml_m7a", ["v2-dev"])
match_table(recs_m7a, title=f"Retrained vs record ({BOOT} bootstrap refits per season; in quick mode the bands are rougher, the point estimates should not move)")
locked_holdout(["m7a_"], skip=("audit",), note="The conversion row is the original engine, which missed its calibration bar (ECE 0.027). v2 has no holdout result: its test is the live 2026 season.")

inputs through 2019: pbp 984,639 rows, A4s 3,584 games, WP states 529,839, M6 plays 111,961 (13s)

  season 2016 done (18s): wp 3s, kicking 15s

  season 2017 done (21s): wp 6s, kicking 14s

  bootstrap 2018 1/50 (17.7s)

  bootstrap 2018 2/50 (18.2s)

  bootstrap 2018 3/50 (22.2s)

  bootstrap 2018 4/50 (19.3s)

  bootstrap 2018 5/50 (15.4s)

  bootstrap 2018 6/50 (15.6s)

  bootstrap 2018 7/50 (15.4s)

  bootstrap 2018 8/50 (15.3s)

  bootstrap 2018 9/50 (14.6s)

  bootstrap 2018 10/50 (15.4s)

  bootstrap 2018 11/50 (15.2s)

  bootstrap 2018 12/50 (16.0s)

  bootstrap 2018 13/50 (15.1s)

  bootstrap 2018 14/50 (13.9s)

  bootstrap 2018 15/50 (13.9s)

  bootstrap 2018 16/50 (13.9s)

  bootstrap 2018 17/50 (13.5s)

  bootstrap 2018 18/50 (13.8s)

  bootstrap 2018 19/50 (13.8s)

  bootstrap 2018 20/50 (13.6s)

  bootstrap 2018 21/50 (14.1s)

  bootstrap 2018 22/50 (13.7s)

  bootstrap 2018 23/50 (14.0s)

  bootstrap 2018 24/50 (14.0s)

  bootstrap 2018 25/50 (14.0s)

  bootstrap 2018 26/50 (13.7s)

  bootstrap 2018 27/50 (14.8s)

  bootstrap 2018 28/50 (13.8s)

  bootstrap 2018 29/50 (14.0s)

  bootstrap 2018 30/50 (13.8s)

  bootstrap 2018 31/50 (13.7s)

  bootstrap 2018 32/50 (14.5s)

  bootstrap 2018 33/50 (14.9s)

  bootstrap 2018 34/50 (14.2s)

  bootstrap 2018 35/50 (13.6s)

  bootstrap 2018 36/50 (13.8s)

  bootstrap 2018 37/50 (13.7s)

  bootstrap 2018 38/50 (14.2s)

  bootstrap 2018 39/50 (14.2s)

  bootstrap 2018 40/50 (15.2s)

  bootstrap 2018 41/50 (14.4s)

  bootstrap 2018 42/50 (15.7s)

  bootstrap 2018 43/50 (15.3s)

  bootstrap 2018 44/50 (14.2s)

  bootstrap 2018 45/50 (13.7s)

  bootstrap 2018 46/50 (13.9s)

  bootstrap 2018 47/50 (13.7s)

  bootstrap 2018 48/50 (14.3s)

  bootstrap 2018 49/50 (15.0s)

  bootstrap 2018 50/50 (14.4s)

  season 2018 done (792s): wp 10s, kicking 15s, components 27s, fourth 740s

  bootstrap 2019 1/50 (25.2s)

  bootstrap 2019 2/50 (22.5s)

  bootstrap 2019 3/50 (17.1s)

  bootstrap 2019 4/50 (17.1s)

  bootstrap 2019 5/50 (17.0s)

  bootstrap 2019 6/50 (17.1s)

  bootstrap 2019 7/50 (16.8s)

  bootstrap 2019 8/50 (17.1s)

  bootstrap 2019 9/50 (21.2s)

  bootstrap 2019 10/50 (23.1s)

  bootstrap 2019 11/50 (20.6s)

  bootstrap 2019 12/50 (20.6s)

  bootstrap 2019 13/50 (19.3s)

  bootstrap 2019 14/50 (19.4s)

  bootstrap 2019 15/50 (19.4s)

  bootstrap 2019 16/50 (20.5s)

  bootstrap 2019 17/50 (19.5s)

  bootstrap 2019 18/50 (21.1s)

  bootstrap 2019 19/50 (22.1s)

  bootstrap 2019 20/50 (19.5s)

  bootstrap 2019 21/50 (19.0s)

  bootstrap 2019 22/50 (19.1s)

  bootstrap 2019 23/50 (19.9s)

  bootstrap 2019 24/50 (23.0s)

  bootstrap 2019 25/50 (21.2s)

  bootstrap 2019 26/50 (19.7s)

  bootstrap 2019 27/50 (19.6s)

  bootstrap 2019 28/50 (19.6s)

  bootstrap 2019 29/50 (19.8s)

  bootstrap 2019 30/50 (22.4s)

  bootstrap 2019 31/50 (22.8s)

  bootstrap 2019 32/50 (20.2s)

  bootstrap 2019 33/50 (19.8s)

  bootstrap 2019 34/50 (19.6s)

  bootstrap 2019 35/50 (19.7s)

  bootstrap 2019 36/50 (18.2s)

  bootstrap 2019 37/50 (17.8s)

  bootstrap 2019 38/50 (17.0s)

  bootstrap 2019 39/50 (16.9s)

  bootstrap 2019 40/50 (17.0s)

  bootstrap 2019 41/50 (16.9s)

  bootstrap 2019 42/50 (17.2s)

  bootstrap 2019 43/50 (17.1s)

  bootstrap 2019 44/50 (16.9s)

  bootstrap 2019 45/50 (16.8s)

  bootstrap 2019 46/50 (17.0s)

  bootstrap 2019 47/50 (16.6s)

  bootstrap 2019 48/50 (18.0s)

  bootstrap 2019 49/50 (31.8s)

  bootstrap 2019 50/50 (27.6s)

  season 2019 done (1081s): wp 12s, kicking 25s, components 56s, fourth 987s

== WP model, REG 2018-2019: 75,104 plays, 509 games (games 416a6f993cb8c9f3) ==

model               Brier  logloss  calibration                        cluster-null ECE p95

m7a_wp             0.1429   0.4356  ECE 0.0047 (null p95 0.0048) ok    0.0246

m7a_wp_isotonic    0.1440   0.4480  ECE 0.0152 (null p95 0.0045) FAIL  0.0241

nflfastr_wp        0.1527   0.4556  ECE 0.0121 (null p95 0.0050) FAIL  0.0266

vegas_wp           0.1380   0.4174  ECE 0.0108 (null p95 0.0049) FAIL  0.0259

  m7a_wp-nflfastr_wp: Brier -0.0098 [-0.0180, -0.0014], log loss -0.0200 [-0.0437, +0.0077]

  m7a_wp-vegas_wp: Brier +0.0049 [+0.0004, +0.0094], log loss +0.0182 [+0.0032, +0.0371]

  m7a_wp-isotonic: Brier -0.0011 [-0.0019, -0.0003], log loss -0.0124 [-0.0282, -0.0020]

  by quarter (Brier m7a / nflfastr / vegas; m7a ECE, rule):

    Q1 n 16,907  0.2019 / 0.2262 / 0.1946   ECE 0.0123 (null p95 0.0116) FAIL

    Q2 n 20,735  0.1622 / 0.1744 / 0.1564   ECE 0.0121 (null p95 0.0099) FAIL

    Q3 n 17,112  0.1312 / 0.1353 / 0.1263   ECE 0.0087 (null p95 0.0097) ok

    Q4 n 20,350  0.0841 / 0.0842 / 0.0820   ECE 0.0066 (null p95 0.0074) ok

  by score difference (posteam):

    -99..-17 n  5,927  0.0126 / 0.0134 / 0.0118   ECE 0.0112 (null p95 0.0048) FAIL

     -16..-9 n 10,473  0.0978 / 0.1085 / 0.0947   ECE 0.0178 (null p95 0.0094) FAIL

      -8..-4 n 11,836  0.1807 / 0.1925 / 0.1771   ECE 0.0411 (null p95 0.0131) FAIL

      -3..-1 n  6,761  0.2288 / 0.2344 / 0.2182   ECE 0.0362 (null p95 0.0178) FAIL

        0..0 n 13,756  0.2234 / 0.2419 / 0.2132   ECE 0.0317 (null p95 0.0127) FAIL

        1..3 n  5,355  0.1936 / 0.2030 / 0.1865   ECE 0.0422 (null p95 0.0181) FAIL

        4..8 n 10,047  0.1371 / 0.1460 / 0.1343   ECE 0.0273 (null p95 0.0120) FAIL

       9..16 n  6,982  0.0614 / 0.0677 / 0.0600   ECE 0.0193 (null p95 0.0087) FAIL

      17..99 n  3,967  0.0082 / 0.0090 / 0.0074   ECE 0.0096 (null p95 0.0045) ok [floor]

== FG make: 1,929 REG attempts: Brier 0.1202, ECE 0.0216 (null p95 0.0238) ok

     18-29 n   458  pred 0.970  made 0.985

     30-39 n   559  pred 0.906  made 0.928

     40-49 n   620  pred 0.776  made 0.737

     50-70 n   292  pred 0.604  made 0.606

== Punts: 4,373 REG punts: CRPS 5.717 yards vs by-spot baseline 5.799, diff -0.082 [-0.119, -0.043]

    P(inside 20) ECE 0.0151 (null p95 0.0208) ok; P(at/beyond 40 or TD) ECE 0.0154 (null p95 0.0151) FAIL

== Conversion (engine, actual go attempts n 1118): Brier 0.2305, ECE 0.0332 (null p95 0.0457) ok

    M6 actual features: 4th downs ECE 0.0439 (null p95 0.0547) ok; 3rd downs ECE 0.0091 (null p95 0.0142) ok; 3rd-and-1/2 ECE 0.0249 (null p95 0.0281) ok

== Selection check (actual minus predicted conversion [95% CI]):

    4th_and_1_engine               n   425  pred 0.676  actual 0.659  -0.017 [-0.060, +0.029]

    4th_and_1_actual_features      n   345  pred 0.668  actual 0.670  +0.002 [-0.050, +0.052]

    3rd_and_1_actual_features      n  1234  pred 0.683  actual 0.690  +0.008 [-0.018, +0.034]

    4th_and_2_engine               n   144  pred 0.542  actual 0.576  +0.034 [-0.046, +0.115]

    4th_and_2_actual_features      n    95  pred 0.547  actual 0.589  +0.042 [-0.055, +0.140]

    3rd_and_2_actual_features      n   853  pred 0.565  actual 0.577  +0.012 [-0.020, +0.044]

    4th_and_1_2_engine             n   569  pred 0.642  actual 0.638  -0.004 [-0.042, +0.036]

== Decision audit (MODEL-ESTIMATED), 7,171 fourth downs, 509 games ==

  choices {'punt': 4312, 'fg': 1741, 'go': 1118}; model recommends {'go': 3065, 'punt': 2722, 'fg': 1384}

  matched 0.651 (clear calls 0.813); toss-up share 0.574

  model-estimated WP given up: total 32.39 wins, 0.0636 per game, 0.0318 per team-game; by choice {'fg': 9.96, 'go': 1.26, 'punt': 21.17}

  top misses (model-estimated WP given up):

    2019 wk 8 LAC v CHI  Q4 1:45 score +1 4th&1 at opp 76: punt (model go) go 0.521 fg 0.147 punt 0.391 lost 0.131

    2019 wk14 MIA v NYJ  Q4 7:03 score -1 4th&1 at opp 29: fg (model go) go 0.551 fg 0.436 punt 0.350 lost 0.115

    2019 wk17 DET v GB  Q4 11:13 score +4 4th&2 at opp 37: fg (model go) go 0.285 fg 0.177 punt 0.136 lost 0.108

    2018 wk15 DEN v CLE  Q4 4:39 score -4 4th&6 at opp 11: fg (model go) go 0.486 fg 0.382 punt 0.323 lost 0.104

    2018 wk14  NO v TB  Q3 10:49 score -11 4th&1 at opp 61: punt (model go) go 0.381 fg 0.192 punt 0.278 lost 0.104

    2019 wk 8 DEN v IND  Q4 1:55 score +1 4th&5 at opp 43: punt (model go) go 0.578 fg 0.437 punt 0.477 lost 0.101

    2019 wk 6 SEA v CLE  Q2 7:28 score -11 4th&2 at opp 2: fg (model go) go 0.330 fg 0.233 punt 0.224 lost 0.097

    2019 wk17 DET v GB   Q4 1:27 score +0 4th&5 at opp 69: punt (model go) go 0.168 fg 0.029 punt 0.075 lost 0.093

    2018 wk 4  KC v DEN  Q3 0:38 score -7 4th&1 at opp 66: punt (model go) go 0.455 fg 0.277 punt 0.365 lost 0.091

    2018 wk12 PIT v DEN  Q4 7:18 score -7 4th&5 at opp 48: punt (model go) go 0.287 fg 0.159 punt 0.199 lost 0.088

  consistency (descriptive):

    went_for_it_model_said_kick  n   193  model WP(choice) 0.325  model WP(rec) 0.332  realized next-snap WP 0.334  won 0.342  conv pred 0.422 actual 0.451

    kicked_model_said_go         n  2140  model WP(choice) 0.443  model WP(rec) 0.457  realized next-snap WP 0.444  won 0.433

    punted_model_said_fg         n   137  model WP(choice) 0.588  model WP(rec) 0.596  realized next-snap WP 0.588  won 0.584

    kicked_fg_model_said_punt    n    32  model WP(choice) 0.559  model WP(rec) 0.567  realized next-snap WP 0.562  won 0.625

    matched                      n  4669  model WP(choice) 0.487  model WP(rec) 0.487  realized next-snap WP 0.487  won 0.477  conv pred 0.524 actual 0.534

    chose fg    n  1741  model 0.5540  realized 0.5543  diff +0.0004 [-0.0022, +0.0029]

    chose go    n  1118  model 0.3204  realized 0.3221  diff +0.0017 [-0.0030, +0.0067]

    chose punt  n  4312  model 0.4780  realized 0.4780  diff +0.0000 [-0.0007, +0.0007]

Acceptance rules on this window: WP calibration ok, Brier gap to nflfastR wp -0.0098 (<= 0.002: ok); conversion ok, FG ok, punt CRPS vs baseline ok (punt event calibration, descriptive: fail)  => PASS

Per season (WP Brier m7a / nflfastr / vegas; FG Brier; punt CRPS vs baseline):

  2016: WP 0.1543 / 0.1638 / 0.1532 (isotonic 0.1553; gap -0.0095 [-0.0192, +0.0004]); FG 0.1131 ECE 0.0196 (null p95 0.0324) ok; punt 5.746 vs 5.854

  2017: WP 0.1350 / 0.1489 / 0.1277 (isotonic 0.1359; gap -0.0139 [-0.0253, -0.0025]); FG 0.1207 ECE 0.0146 (null p95 0.0307) ok; punt 5.728 vs 5.822

  2018: WP 0.1453 / 0.1536 / 0.1393 (isotonic 0.1468; gap -0.0083 [-0.0189, +0.0026]); FG 0.1125 ECE 0.0183 (null p95 0.0332) ok; punt 5.947 vs 6.005

  2019: WP 0.1406 / 0.1519 / 0.1366 (isotonic 0.1413; gap -0.0113 [-0.0239, +0.0018]); FG 0.1276 ECE 0.0274 (null p95 0.0336) ok; punt 5.482 vs 5.588

Runs written to data/raw/ml/_train_all_runs/ (label m7adev)

dev total 1947s

inputs through 2019: pbp 984,639 rows, A4s 3,584 games, WP states 529,839, M6 plays 111,961 (13s)

Mix tuning on training seasons 2010-2017 (call log loss, n 3,680): best half-life 2.0, k_bucket 0, k_cell 100 (0.42772); team k 10 (0.42706); v1 share 0.42958. Defaults match: True

  v2 offsets 2018: fold 2016 (28,051 M6 plays, 469 attempts, 6s)

  v2 offsets 2018: fold 2017 (28,367 M6 plays, 480 attempts, 4s)

  season 2018 done (127s); v1 reproduction max |diff| 0

  v2 offsets 2019: fold 2016 (55,662 M6 plays, 469 attempts, 6s)

  v2 offsets 2019: fold 2017 (55,978 M6 plays, 480 attempts, 6s)

  v2 offsets 2019: fold 2018 (56,418 M6 plays, 526 attempts, 7s)

  season 2019 done (116s); v1 reproduction max |diff| 0

== v1 reproduction on dev (option values and conversion vs fourth_m7adev.parquet): {2018: 0.0, 2019: 0.0} -> REPRODUCED

== Diagnosis, dev go attempts n 1118 ==

  run share by distance (actual dev / engine v1):

       1 n  425  0.711 / 0.736   [goal 1-5 88: 0.69/0.74; red 6-20 60: 0.75/0.74; opp 21-50 174: 0.67/0.74; own 51+ 103: 0.78/0.74]

       2 n  144  0.181 / 0.229   [goal 1-5 15: 0.13/0.23; red 6-20 19: 0.16/0.23; opp 21-50 80: 0.19/0.23; own 51+ 30: 0.20/0.23]

     3-5 n  254  0.071 / 0.103   [goal 1-5 29: 0.07/0.10; red 6-20 32: 0.06/0.10; opp 21-50 141: 0.04/0.10; own 51+ 52: 0.15/0.10]

      6+ n  295  0.047 / 0.092   [goal 1-5 1: 0.00/0.12; red 6-20 40: 0.00/0.10; opp 21-50 147: 0.02/0.09; own 51+ 107: 0.10/0.08]

  engine                   Brier 0.2305  ECE 0.0332 (null p95 0.0457) ok  4th-and-1 -0.017, 4th-and-2 +0.034, 4th-and-3-5 -0.011, 4th-and-6+ +0.069, 4th-and-1-2 -0.004

  oracle_mix_dev_share     Brier 0.2303  ECE 0.0324 (null p95 0.0444) ok  4th-and-1 -0.013, 4th-and-2 +0.037, 4th-and-3-5 -0.012, 4th-and-6+ +0.065, 4th-and-1-2 +0.000

  oracle_actual_call       Brier 0.2313  ECE 0.0426 (null p95 0.0436) ok  4th-and-1 -0.014, 4th-and-2 +0.037, 4th-and-3-5 -0.012, 4th-and-6+ +0.066, 4th-and-1-2 -0.001

  structure: same call, averaged configurations vs the play's own structure (M6 subset):

     run    1 n  241  actual 0.693  avg-structure 0.725  own-structure 0.720

     run    2 n   19  actual 0.579  avg-structure 0.583  own-structure 0.587

     run  3-5 n   11  actual 0.545  avg-structure 0.480  own-structure 0.456

     run   6+ n    8  actual 0.250  avg-structure 0.242  own-structure 0.216

    pass    1 n  103  actual 0.612  avg-structure 0.546  own-structure 0.545

    pass    2 n   75  actual 0.573  avg-structure 0.534  own-structure 0.538

    pass  3-5 n  134  actual 0.455  avg-structure 0.476  own-structure 0.479

    pass   6+ n  110  actual 0.409  avg-structure 0.309  own-structure 0.310

    subset n 701: engine ECE 0.0312, actual call + avg structure 0.0479, actual call + own structure 0.0422

  M6 training domain (garbage-time filter) by distance (actual / engine):

    inside M6 training domain           1 n  344  0.669 / 0.676

    inside M6 training domain           2 n   94  0.574 / 0.545

    inside M6 training domain         3-5 n  145  0.462 / 0.477

    inside M6 training domain          6+ n  118  0.398 / 0.303

    outside (garbage-time filter)       1 n   81  0.617 / 0.673

    outside (garbage-time filter)       2 n   50  0.580 / 0.537

    outside (garbage-time filter)     3-5 n  109  0.459 / 0.466

    outside (garbage-time filter)      6+ n  177  0.305 / 0.254

  offsets (logit, run / pass by distance 1, 2, 3-5, 6+):

    2018: run [-0.071, -0.321, -0.137, 0.109]  pass [-0.037, 0.212, 0.136, 0.052]  n 949

    2019: run [-0.071, -0.228, -0.11, 0.2]  pass [0.133, 0.244, 0.086, 0.151]  n 1475

== Candidates, dev 2018-2019, conversion on actual go attempts (n 1118) ==

cand      Brier     ECE     p95  ok  vs v1 Brier [95% CI]                      vs best (SE)  1SE   actual-pred: 4th-and-1 / 2 / 3-5 / 6+ / 1-2

v1      0.23050  0.0332  0.0457   y  +0.00000 [+0.00000, +0.00000]       +0.00024 (0.00012)        -0.017 / +0.034 / -0.011 / +0.069 / -0.004

v2a     0.23030  0.0333  0.0461   y  -0.00020 [-0.00039, -0.00002]       +0.00004 (0.00007)  yes   -0.014 / +0.037 / -0.012 / +0.067 / -0.001

v2b     0.23026  0.0351  0.0450   y  -0.00024 [-0.00047, -0.00000]       +0.00000 (0.00000)  yes   -0.014 / +0.037 / -0.012 / +0.067 / -0.001

v2d     0.23053  0.0213  0.0442   y  +0.00003 [-0.00113, +0.00122]       +0.00027 (0.00057)  yes   -0.009 / +0.006 / -0.033 / +0.048 / -0.005

v2ad    0.23041  0.0190  0.0435   y  -0.00009 [-0.00132, +0.00123]       +0.00015 (0.00062)  yes   -0.007 / +0.004 / -0.034 / +0.046 / -0.005  *

v2bd    0.23036  0.0194  0.0440   y  -0.00014 [-0.00137, +0.00118]       +0.00010 (0.00062)  yes   -0.007 / +0.003 / -0.034 / +0.046 / -0.005

Best: v2b. Within one SE (and calibrated): ['v2a', 'v2b', 'v2d', 'v2ad', 'v2bd']. Original rule (simplest): v2a. 4th-and-1/2 gaps under 0.02: ['v2d', 'v2ad', 'v2bd']. CHOSEN (corrected rule, lowest ECE): v2ad (code V2_CHOSEN v2ad: match)

  v1    selection: 4th-and-1 n 425 pred 0.676 act 0.659 -0.017 [-0.060, +0.029]; 4th-and-2 n 144 pred 0.542 act 0.576 +0.034 [-0.046, +0.115]; 4th-and-1-2 n 569 pred 0.642 act 0.638 -0.004 [-0.042, +0.036]

  v2a   selection: 4th-and-1 n 425 pred 0.673 act 0.659 -0.014 [-0.058, +0.032]; 4th-and-2 n 144 pred 0.540 act 0.576 +0.037 [-0.044, +0.117]; 4th-and-1-2 n 569 pred 0.639 act 0.638 -0.001 [-0.039, +0.038]

  v2b   selection: 4th-and-1 n 425 pred 0.673 act 0.659 -0.014 [-0.057, +0.032]; 4th-and-2 n 144 pred 0.540 act 0.576 +0.037 [-0.044, +0.117]; 4th-and-1-2 n 569 pred 0.639 act 0.638 -0.001 [-0.039, +0.038]

  v2d   selection: 4th-and-1 n 425 pred 0.668 act 0.659 -0.009 [-0.053, +0.037]; 4th-and-2 n 144 pred 0.570 act 0.576 +0.006 [-0.076, +0.086]; 4th-and-1-2 n 569 pred 0.643 act 0.638 -0.005 [-0.043, +0.034]

  v2ad  selection: 4th-and-1 n 425 pred 0.666 act 0.659 -0.007 [-0.051, +0.039]; 4th-and-2 n 144 pred 0.573 act 0.576 +0.004 [-0.078, +0.083]; 4th-and-1-2 n 569 pred 0.643 act 0.638 -0.005 [-0.043, +0.035]

  v2bd  selection: 4th-and-1 n 425 pred 0.666 act 0.659 -0.007 [-0.051, +0.039]; 4th-and-2 n 144 pred 0.573 act 0.576 +0.003 [-0.078, +0.083]; 4th-and-1-2 n 569 pred 0.642 act 0.638 -0.005 [-0.043, +0.035]

  decisions vs v1 (dev point estimates, model-estimated): v2a changed 26 of 7171 (mean |dWP go| 0.0003); v2b changed 27 of 7171 (mean |dWP go| 0.0003); v2d changed 255 of 7171 (mean |dWP go| 0.0025); v2ad changed 289 of 7171 (mean |dWP go| 0.0027); v2bd changed 284 of 7171 (mean |dWP go| 0.0027)

  real-data leakcheck (2019 wk 9, 195 decisions): mix diff 0, week-share diff 0; controls: next week 0.0193, prior-season calls 0.299 -> LEAK-FREE

v2-dev total 261s

[9. M7a win prob + fourth down: 2209s]

**Retrained vs record (50 bootstrap refits per season; in quick mode the bands are rougher, the point estimates should not move)**: 14 of 14 runs match (tolerance max(5e-05, 0.2% of the record) on every metric).

**Locked 2020-2025 holdout, loaded from `experiments/runs/` (not recomputed)**. The conversion row is the original engine, which missed its calibration bar (ECE 0.027). v2 has no holdout result: its test is the live 2026 season.

## 10. M7b: early-down play calling

Run versus pass by personnel, estimated with causal methods (propensity scores, doubly-robust AIPW, off-policy
evaluation) and checked with a placebo. **Passed**: the recommended policy beats observed play calling by
+0.052 EPA per play on the holdout, with a placebo that includes zero.

In [13]:
with section("10. M7b play calling"):
    recs_m7b = run_main("ml_m7b", ["dev"])
match_table(recs_m7b)
locked_holdout(["m7b_"])

frame through 2019: 78,564 early-down plays in 1,068 games (8s)

main pipeline:

  season 2018: 19,449 plays, train 39,508 (13s: cross_fit 6s, fit_predict 6s, cells_ope 1s)

  season 2019: 19,607 plays, train 58,957 (26s: cross_fit 18s, fit_predict 7s, cells_ope 1s)

placebo (actions shuffled within season x cell, whole pipeline rerun):

  season 2018: 19,449 plays, train 39,508 (8s: cross_fit 4s, fit_predict 3s, cells_ope 0s)

  season 2019: 19,607 plays, train 58,957 (14s: cross_fit 9s, fit_predict 4s, cells_ope 0s)

=== M7b 2018-2019: 39,056 early-down plays, 534 games ===

action shares: 11_run 0.215, 11_pass 0.299, 12_run 0.114, 12_pass 0.124, 21_run 0.054, 21_pass 0.049, 13_run 0.021, 13_pass 0.017, 10_run 0.003, 10_pass 0.007, oth_run 0.062, oth_pass 0.036

overlap (main, thr 0.05): >=2 eligible 1.000; mean eligible 5.28 of 12; pairs eligible 0.440; observed action eligible 0.886

   by action: 11_run 1.00, 11_pass 1.00, 12_run 0.86, 12_pass 0.93, 21_run 0.39, 21_pass 0.37, 13_run 0.08, 13_pass 0.02, 10_run 0.00, 10_pass 0.01, oth_run 0.46, oth_pass 0.16

overlap (thr10, thr 0.1): >=2 eligible 0.993; mean eligible 3.54 of 12; pairs eligible 0.295; observed action eligible 0.757

   by action: 11_run 0.98, 11_pass 0.98, 12_run 0.53, 12_pass 0.67, 21_run 0.12, 21_pass 0.09, 13_run 0.01, 13_pass 0.00, 10_run 0.00, 10_pass 0.00, oth_run 0.13, oth_pass 0.03

propensity: log loss 1.8487 vs cell shares 1.9610 (-0.1124 [-0.1249, -0.1001]); pass share pred 0.524 obs 0.531

   11_run   share 0.215 pred 0.228 ECE 0.0125 (p95 0.0059) FAIL

   11_pass  share 0.299 pred 0.301 ECE 0.0079 (p95 0.0067) ok

   12_run   share 0.114 pred 0.113 ECE 0.0028 (p95 0.0039) ok

   12_pass  share 0.124 pred 0.124 ECE 0.0064 (p95 0.0042) ok

   21_run   share 0.054 pred 0.050 ECE 0.0044 (p95 0.0026) ok

   21_pass  share 0.049 pred 0.046 ECE 0.0035 (p95 0.0024) ok

   13_run   share 0.021 pred 0.020 ECE 0.0005 (p95 0.0015) ok

   13_pass  share 0.017 pred 0.015 ECE 0.0021 (p95 0.0012) ok

   10_run   share 0.003 pred 0.002 ECE 0.0010 (p95 0.0005) ok

   10_pass  share 0.007 pred 0.004 ECE 0.0029 (p95 0.0008) ok

   oth_run  share 0.062 pred 0.063 ECE 0.0044 (p95 0.0032) ok

   oth_pass share 0.036 pred 0.035 ECE 0.0023 (p95 0.0020) ok

outcome: EPA MSE 1.4622 vs cell x action mean 1.4795 (-0.0173 [-0.0226, -0.0122]), constant 1.4728; success Brier 0.2393 vs 0.2433; success ECE 0.0068 ok

OPE [main]: EPA/play +0.0743 [+0.0514, +0.0963]; success +0.0442 [+0.0355, +0.0532]; policy applies to 0.553 of plays (changes the call on 0.452); +0.1343 per affected play

OPE [thr10]: EPA/play +0.0651 [+0.0460, +0.0822]; success +0.0403 [+0.0337, +0.0469]; policy applies to 0.475 of plays (changes the call on 0.368); +0.1371 per affected play

OPE [trim10]: EPA/play +0.0743 [+0.0518, +0.0959]; success +0.0451 [+0.0370, +0.0533]; policy applies to 0.565 of plays (changes the call on 0.462); +0.1314 per affected play

observed-policy check: DR +0.0156 vs mean EPA +0.0170: -0.0015 [-0.0027, -0.0003]; success -0.0010 [-0.0018, -0.0002]

PLACEBO: EPA/play -0.0078 [-0.0181, +0.0025]; applies to 0.061 of plays

recs for 2018: 14 of 60 cells clear (0.233; 0.543 of plays); best {'12_pass': 10, '11_pass': 4}

   1-10+ | opp 49-21 | within 3        n  2505 best 12_pass  gain +0.338 [+0.197, +0.496] (DR +0.346 vs obs +0.008)

   1-10+ | red zone | within 3         n   705 best 11_pass  gain +0.359 [+0.188, +0.530] (DR +0.372 vs obs +0.012)

   2-mid | opp 49-21 | trail 4+        n   464 best 12_pass  gain +0.481 [+0.143, +0.861] (DR +0.553 vs obs +0.072)

   2-long | own 1-20 | within 3        n   529 best 11_pass  gain +0.266 [+0.086, +0.472] (DR +0.379 vs obs +0.113)

   1-10+ | own 21-50 | lead 4+         n  2536 best 12_pass  gain +0.211 [+0.081, +0.342] (DR +0.233 vs obs +0.022)

   1-10+ | own 21-50 | within 3        n  4962 best 11_pass  gain +0.147 [+0.070, +0.222] (DR +0.136 vs obs -0.011)

recs for 2019: 17 of 60 cells clear (0.283; 0.611 of plays); best {'12_pass': 11, '11_pass': 4, '11_run': 2}

   1-10+ | red zone | within 3         n  1065 best 11_pass  gain +0.320 [+0.185, +0.462] (DR +0.326 vs obs +0.005)

   1-10+ | opp 49-21 | within 3        n  3774 best 12_pass  gain +0.263 [+0.140, +0.380] (DR +0.268 vs obs +0.005)

   2-long | own 1-20 | within 3        n   739 best 11_pass  gain +0.274 [+0.124, +0.443] (DR +0.325 vs obs +0.051)

   1-10+ | own 1-20 | within 3         n  1516 best 12_pass  gain +0.218 [+0.090, +0.344] (DR +0.170 vs obs -0.048)

   2-long | own 21-50 | within 3       n  3001 best 12_pass  gain +0.214 [+0.088, +0.343] (DR +0.183 vs obs -0.031)

   2-mid | opp 49-21 | lead 4+         n   450 best 12_pass  gain +0.349 [+0.077, +0.637] (DR +0.354 vs obs +0.006)

recs [thr10]: 2018: 11/60; 2019: 18/60

recs [trim10]: 2018: 15/60; 2019: 17/60

placebo recs: 2018: 5/60 clear; 2019: 5/60 clear

RULES: OPE CI low +0.0514 (pass); placebo CI [-0.0181, +0.0025] (pass) -> PASS

Per season:

  2018: OPE +0.0683 [+0.0401, +0.0981]; success +0.0434 [+0.0319, +0.0550]; placebo -0.0092 [-0.0246, +0.0064]; observed check -0.0024 [-0.0042, -0.0006]; clear share 0.233

  2019: OPE +0.0803 [+0.0435, +0.1173]; success +0.0449 [+0.0315, +0.0584]; placebo -0.0065 [-0.0210, +0.0078]; observed check -0.0005 [-0.0021, +0.0011]; clear share 0.283

Team view MIN 2019: 622 plays, pass share 0.471 (league 0.528), EPA -0.038; league policy on its plays -0.0593 [-0.3237, +0.1853] (applies 0.62)

   13_run   team 0.061 league 0.019 gain +0.181 [-0.257, +0.599] (n elig 134)

   oth_run  team 0.064 league 0.068 gain +0.176 [-0.210, +0.819] (n elig 302)

   21_run   team 0.180 league 0.054 gain +0.156 [-0.129, +0.499] (n elig 578)

   11_pass  team 0.039 league 0.284 gain +0.088 [-0.076, +0.260] (n elig 615)

   21_pass  team 0.140 league 0.051 gain +0.043 [-0.448, +0.520] (n elig 573)

   11_run   team 0.080 league 0.204 gain -0.013 [-0.212, +0.217] (n elig 622)

   12_run   team 0.141 league 0.123 gain -0.261 [-0.528, -0.011] (n elig 545)

   12_pass  team 0.211 league 0.128 gain -0.265 [-0.763, +0.151] (n elig 611)

Runs written to data/raw/ml/_train_all_runs/ (label m7bdev)

dev total 75s

[10. M7b play calling: 75s]

**Retrained vs the committed development record**: 8 of 8 runs match (tolerance max(5e-05, 0.2% of the record) on every metric).

**Locked 2020-2025 holdout, loaded from `experiments/runs/` (not recomputed)**

## 11. M8: game model v2

Margin and EPA targets, model blending, an opponent-adjusted QB value with injury-exit cleaning, early-season
(new QB, new coach) and context features (travel, rest, altitude, venue), and stacking. A **negative result**:
nothing beat C2d beyond noise on the development seasons, so A4s stays the headline and C2d the shadow. No holdout
was run.

In [14]:
with section("11. M8 game model v2"):
    recs_m8 = []
    if FULL:
        recs_m8 += run_main("ml_m8", ["tune"])
    recs_m8 += run_main("ml_m8", ["dev"])
match_table(recs_m8)
print("No holdout result exists for M8 by design: nothing beat C2d on the development seasons.")

== QB v2 tuning, 2000-2005: 3036 starter-games, k 100 ==
baseline (M3 value) wMSE 0.10918; v2 code path with nothing on 0.10918 (must match)

(a) opponent adjustment (prediction Q + D[opponent] + h*home; and Q alone):
 lam_d  wmse_opp  wmse_q_only
  25.0  0.115791     0.111649
  50.0  0.112501     0.110953
 100.0  0.109959     0.110393
 200.0  0.108448     0.110018
 400.0  0.107964     0.109809
 800.0  0.108168     0.109711
1600.0  0.108604     0.109672
3200.0  0.108985     0.109658

(b) injury-exit cleaning (partial QB-games: 17.8% of QB-game rows, 2000-2005):
 exit_weight   wmse_b  wmse_ab
        0.00 0.109071 0.108255
        0.25 0.109074 0.108119
        0.50 0.109095 0.108030
        0.75 0.109131 0.107980
        1.00 0.109182 0.107964
chosen: lam_d 400; exit_weight 0 (b alone), 1 (with a). 5.7s

== Kalman carry-over, REG weeks 1-4 of 2000-2005 (356 games) ==
TUNED gamma 0.4832, q_season 14.431: -loglik 1410.55
early-season optimum gamma 0.5010, q_season 23.106: -loglik 1409.37 (74 evaluations, 2.0s)
gamma profile (q_season fixed): 0.3 1413.04, 0.4 1411.36, 0.5 1410.46, 0.6 1410.41, 0.7 1411.28, 0.8 1413.10

== Blend weight, leave-one-season-out over REG 2001-2005 (n 1272), A4s features ==
  w  logloss  corr_target_margin
0.0 0.632534            0.850503
0.1 0.632281            0.875741
0.2 0.632063            0.899616
0.3 0.631882            0.921730
0.4 0.631742            0.941689
0.5 0.631644            0.959127
0.6 0.631592            0.973722
0.7 0.631588            0.985225
0.8 0.631635            0.993469
0.9 0.631736            0.998384
1.0 0.631893            1.000000
chosen w 0.7 (1.3s)

Freeze in code:
  qb.TUNED_V2_A = QBv2(lam_d=400)
  qb.TUNED_V2_B = QBv2(exit_weight=0)
  qb.TUNED_V2_AB = QBv2(lam_d=400, exit_weight=1)
  kalman.TUNED_CARRYOVER = replace(TUNED, gamma=0.50096, q_season=23.106)
  ml_m8.BLEND_W = 0.7

DEV 2006-2019: n = 3450, games hash 52b8194df3a2ebf4. Features 10.1s (elo 0.0s, raw_epa 0.2s, ratings 0.2s, qb 2.2s, kalman 0.2s, qb_v2 6.6s, early 0.4s, context 0.3s)

A4s reproduction: 0.21509 (M3 0.2151); C2d 0.21413 (M3b 0.2141)
Components that beat C2d on their own: {'E3b': 'E3b'}; best E1 on C2d features E1_C2d_margin_logit (beats C2d)

Ladder, DEV 2006-2019, n = 3450. Paired bootstrap (2,000 reps, seed 20261003); ECE ok = <= p95 of a calibrated forecaster at this n, or <= 0.01.
step                     brier  logloss    acc    ece    p95 ok  vs A4s [95% CI]            vs C2d [95% CI]             1SE
A4s                     0.2151   0.6197  0.647  0.011  0.025  y  +0.0000 [+0.0000, +0.0000] +0.0010 [-0.0000, +0.0019]
C2d                     0.2141   0.6175  0.650  0.014  0.026  y  -0.0010 [-0.0019, +0.0000] +0.0000 [+0.0000, +0.0000]  yes *
E1_A4s_margin_normal    0.2151   0.6199  0.648  0.013  0.025  y  +0.0000 [-0.0004, +0.0005] +0.0010 [-0.0001, +0.0021]
E1_A4s_margin_logit     0.2150   0.6194  0.647  0.010  0.025  y  -0.0001 [-0.0003, +0.0001] +0.0008 [-0.0002, +0.0018]
E1_A4s_epa_normal       0.2156   0.6212  0.647  0.022  0.025  y  +0.0005 [-0.0002, +0.0012] +0.0015 [+0.0003, +0.0026]
E1_A4s_epa_logit        0.2154   0.6206  0.646  0.015  0.025  y  +0.0003 [-0.0003, +0.0009] +0.0013 [+0.0002, +0.0023]
E1_A4s_blend_normal     0.2152   0.6200  0.648  0.014  0.025  y  +0.0001 [-0.0004, +0.0005] +0.0010 [+0.0000, +0.0020]
E1_A4s_blend_logit      0.2150   0.6195  0.648  0.011  0.025  y  -0.0001 [-0.0003, +0.0001] +0.0008 [-0.0001, +0.0018]
E1_C2d_margin_normal    0.2142   0.6178  0.651  0.014  0.026  y  -0.0009 [-0.0017, -0.0000] +0.0001 [-0.0004, +0.0006]  yes
E1_C2d_margin_logit     0.2140   0.6172  0.650  0.015  0.026  y  -0.0011 [-0.0019, -0.0003] -0.0002 [-0.0004, +0.0001]  yes
E1_C2d_epa_normal       0.2143   0.6182  0.650  0.014  0.025  y  -0.0008 [-0.0018, +0.0003] +0.0002 [-0.0003, +0.0007]
E1_C2d_epa_logit        0.2141   0.6175  0.650  0.015  0.026  y  -0.0010 [-0.0020, +0.0000] -0.0000 [-0.0003, +0.0003]  yes
E1_C2d_blend_normal     0.2142   0.6179  0.652  0.015  0.026  y  -0.0009 [-0.0018, +0.0001] +0.0001 [-0.0004, +0.0006]  yes
E1_C2d_blend_logit      0.2140   0.6172  0.650  0.016  0.026  y  -0.0011 [-0.0020, -0.0002] -0.0001 [-0.0004, +0.0001]  yes
E2a                     0.2144   0.6181  0.649  0.014  0.026  y  -0.0007 [-0.0017, +0.0003] +0.0003 [+0.0000, +0.0005]
E2b                     0.2142   0.6178  0.651  0.013  0.026  y  -0.0009 [-0.0019, +0.0001] +0.0001 [-0.0002, +0.0004]
E2ab                    0.2145   0.6184  0.648  0.016  0.026  y  -0.0005 [-0.0016, +0.0004] +0.0004 [+0.0001, +0.0007]
E3a                     0.2143   0.6178  0.649  0.020  0.026  y  -0.0008 [-0.0018, +0.0002] +0.0001 [-0.0003, +0.0006]
E3b                     0.2139   0.6170  0.654  0.016  0.025  y  -0.0011 [-0.0022, -0.0001] -0.0002 [-0.0006, +0.0002]  yes
E3c                     0.2142   0.6176  0.651  0.015  0.026  y  -0.0009 [-0.0019, +0.0001] +0.0000 [-0.0002, +0.0002]  yes
E3abc                   0.2141   0.6173  0.653  0.020  0.025  y  -0.0010 [-0.0021, +0.0001] -0.0000 [-0.0007, +0.0006]  yes
E4_travel               0.2143   0.6178  0.649  0.015  0.026  y  -0.0008 [-0.0021, +0.0004] +0.0001 [-0.0006, +0.0009]  yes
E4_body                 0.2142   0.6176  0.647  0.016  0.025  y  -0.0009 [-0.0023, +0.0004] +0.0001 [-0.0009, +0.0011]  yes
E4_rest                 0.2141   0.6175  0.652  0.017  0.026  y  -0.0009 [-0.0021, +0.0001] +0.0000 [-0.0006, +0.0006]  yes
E4_alt                  0.2143   0.6181  0.651  0.013  0.026  y  -0.0008 [-0.0018, +0.0003] +0.0002 [-0.0002, +0.0006]
E4_venue                0.2146   0.6185  0.654  0.008  0.025  y  -0.0005 [-0.0017, +0.0008] +0.0005 [-0.0004, +0.0012]
E4_all                  0.2151   0.6195  0.648  0.018  0.025  y  -0.0000 [-0.0019, +0.0017] +0.0009 [-0.0006, +0.0024]
E4w                     0.2145   0.6183  0.650  0.013  0.026  y  -0.0006 [-0.0017, +0.0004] +0.0004 [-0.0001, +0.0008]
E5                      0.2139   0.6170  0.654  0.016  0.025  y  -0.0011 [-0.0022, -0.0001] -0.0002 [-0.0006, +0.0002]  yes
E5m                     0.2140   0.6172  0.652  0.015  0.026  y  -0.0011 [-0.0019, -0.0002] -0.0001 [-0.0005, +0.0003]  yes
E6                      0.2146   0.6184  0.650  0.014  0.025  y  -0.0005 [-0.0014, +0.0004] +0.0004 [-0.0000, +0.0010]
E6b                     0.2145   0.6184  0.652  0.012  0.026  y  -0.0005 [-0.0013, +0.0003] +0.0004 [-0.0001, +0.0009]

Elo v2                  0.2178   0.6255  0.641  0.015
Market (benchmark)      0.2106   0.6096  0.663  0.018
Leak alarm (better than A4s by more than 0.006): none
Best: E3b (0.21394). Within one SE: ['C2d', 'E1_C2d_margin_normal', 'E1_C2d_margin_logit', 'E1_C2d_epa_logit', 'E1_C2d_blend_normal', 'E1_C2d_blend_logit', 'E3b', 'E3c', 'E3abc', 'E4_travel', 'E4_body', 'E4_rest', 'E5', 'E5m']. CHOSEN (one-SE rule): C2d.
DEV acceptance (beats A4s with CI excluding 0, ECE check): FAIL (C2d minus A4s -0.0010 [-0.0019, +0.0000]; minus C2d +0.0000 [+0.0000, +0.0000]; ECE 0.0142)

Splits (Brier; minus A4s and minus C2d [95% CI]; A4s / C2d / market Brier on the same games):
  C2d:
    weeks_1_4    n  751 0.2237  vsA4s -0.0006 [-0.0023, +0.0011]  vsC2d +0.0000 [+0.0000, +0.0000]  (A4s 0.2243, C2d 0.2237, mkt 0.2198)
    weeks_5_9    n  969 0.2124  vsA4s -0.0002 [-0.0019, +0.0016]  vsC2d +0.0000 [+0.0000, +0.0000]  (A4s 0.2126, C2d 0.2124, mkt 0.2095)
    weeks_10_18  n 1730 0.2109  vsA4s -0.0016 [-0.0029, -0.0002]  vsC2d +0.0000 [+0.0000, +0.0000]  (A4s 0.2125, C2d 0.2109, mkt 0.2072)
    changed      n  664 0.2150  vsA4s -0.0000 [-0.0021, +0.0021]  vsC2d +0.0000 [+0.0000, +0.0000]  (A4s 0.2150, C2d 0.2150, mkt 0.2072)
    unchanged    n 2786 0.2139  vsA4s -0.0012 [-0.0022, -0.0001]  vsC2d +0.0000 [+0.0000, +0.0000]  (A4s 0.2151, C2d 0.2139, mkt 0.2114)
    short_week   n  179 0.2003  vsA4s -0.0037 [-0.0077, +0.0001]  vsC2d +0.0000 [+0.0000, +0.0000]  (A4s 0.2041, C2d 0.2003, mkt 0.1893)
  E1_C2d_margin_logit:
    weeks_1_4    n  751 0.2234  vsA4s -0.0009 [-0.0024, +0.0005]  vsC2d -0.0003 [-0.0008, +0.0001]  (A4s 0.2243, C2d 0.2237, mkt 0.2198)
    weeks_5_9    n  969 0.2120  vsA4s -0.0006 [-0.0020, +0.0009]  vsC2d -0.0004 [-0.0010, +0.0001]  (A4s 0.2126, C2d 0.2124, mkt 0.2095)
    weeks_10_18  n 1730 0.2110  vsA4s -0.0015 [-0.0026, -0.0003]  vsC2d +0.0001 [-0.0003, +0.0005]  (A4s 0.2125, C2d 0.2109, mkt 0.2072)
    changed      n  664 0.2145  vsA4s -0.0005 [-0.0023, +0.0012]  vsC2d -0.0005 [-0.0012, +0.0002]  (A4s 0.2150, C2d 0.2150, mkt 0.2072)
    unchanged    n 2786 0.2139  vsA4s -0.0012 [-0.0021, -0.0004]  vsC2d -0.0001 [-0.0004, +0.0002]  (A4s 0.2151, C2d 0.2139, mkt 0.2114)
    short_week   n  179 0.2006  vsA4s -0.0035 [-0.0066, -0.0003]  vsC2d +0.0003 [-0.0008, +0.0013]  (A4s 0.2041, C2d 0.2003, mkt 0.1893)
  E2a:
    weeks_1_4    n  751 0.2235  vsA4s -0.0007 [-0.0026, +0.0010]  vsC2d -0.0002 [-0.0007, +0.0003]  (A4s 0.2243, C2d 0.2237, mkt 0.2198)
    weeks_5_9    n  969 0.2126  vsA4s +0.0000 [-0.0018, +0.0018]  vsC2d +0.0002 [-0.0002, +0.0006]  (A4s 0.2126, C2d 0.2124, mkt 0.2095)
    weeks_10_18  n 1730 0.2115  vsA4s -0.0010 [-0.0024, +0.0004]  vsC2d +0.0005 [+0.0002, +0.0008]  (A4s 0.2125, C2d 0.2109, mkt 0.2072)
    changed      n  664 0.2158  vsA4s +0.0008 [-0.0015, +0.0031]  vsC2d +0.0008 [-0.0001, +0.0017]  (A4s 0.2150, C2d 0.2150, mkt 0.2072)
    unchanged    n 2786 0.2141  vsA4s -0.0010 [-0.0021, +0.0001]  vsC2d +0.0002 [-0.0000, +0.0003]  (A4s 0.2151, C2d 0.2139, mkt 0.2114)
    short_week   n  179 0.1999  vsA4s -0.0042 [-0.0081, -0.0004]  vsC2d -0.0005 [-0.0016, +0.0006]  (A4s 0.2041, C2d 0.2003, mkt 0.1893)

  E2b:
    weeks_1_4    n  751 0.2239  vsA4s -0.0003 [-0.0021, +0.0015]  vsC2d +0.0002 [-0.0003, +0.0007]  (A4s 0.2243, C2d 0.2237, mkt 0.2198)
    weeks_5_9    n  969 0.2124  vsA4s -0.0002 [-0.0021, +0.0017]  vsC2d -0.0000 [-0.0006, +0.0006]  (A4s 0.2126, C2d 0.2124, mkt 0.2095)
    weeks_10_18  n 1730 0.2111  vsA4s -0.0014 [-0.0029, -0.0000]  vsC2d +0.0001 [-0.0003, +0.0005]  (A4s 0.2125, C2d 0.2109, mkt 0.2072)
    changed      n  664 0.2147  vsA4s -0.0002 [-0.0026, +0.0021]  vsC2d -0.0002 [-0.0013, +0.0009]  (A4s 0.2150, C2d 0.2150, mkt 0.2072)
    unchanged    n 2786 0.2141  vsA4s -0.0010 [-0.0020, +0.0001]  vsC2d +0.0002 [-0.0000, +0.0004]  (A4s 0.2151, C2d 0.2139, mkt 0.2114)
    short_week   n  179 0.2017  vsA4s -0.0024 [-0.0070, +0.0021]  vsC2d +0.0013 [-0.0003, +0.0032]  (A4s 0.2041, C2d 0.2003, mkt 0.1893)
  E2ab:
    weeks_1_4    n  751 0.2238  vsA4s -0.0005 [-0.0023, +0.0013]  vsC2d +0.0000 [-0.0006, +0.0007]  (A4s 0.2243, C2d 0.2237, mkt 0.2198)
    weeks_5_9    n  969 0.2125  vsA4s -0.0001 [-0.0020, +0.0019]  vsC2d +0.0001 [-0.0006, +0.0008]  (A4s 0.2126, C2d 0.2124, mkt 0.2095)
    weeks_10_18  n 1730 0.2117  vsA4s -0.0008 [-0.0023, +0.0007]  vsC2d +0.0007 [+0.0003, +0.0012]  (A4s 0.2125, C2d 0.2109, mkt 0.2072)
    changed      n  664 0.2156  vsA4s +0.0006 [-0.0019, +0.0031]  vsC2d +0.0007 [-0.0006, +0.0020]  (A4s 0.2150, C2d 0.2150, mkt 0.2072)
    unchanged    n 2786 0.2143  vsA4s -0.0008 [-0.0019, +0.0003]  vsC2d +0.0004 [+0.0001, +0.0006]  (A4s 0.2151, C2d 0.2139, mkt 0.2114)
    short_week   n  179 0.2011  vsA4s -0.0029 [-0.0074, +0.0015]  vsC2d +0.0008 [-0.0009, +0.0026]  (A4s 0.2041, C2d 0.2003, mkt 0.1893)
  E3a:
    weeks_1_4    n  751 0.2239  vsA4s -0.0004 [-0.0022, +0.0015]  vsC2d +0.0002 [-0.0005, +0.0010]  (A4s 0.2243, C2d 0.2237, mkt 0.2198)
    weeks_5_9    n  969 0.2126  vsA4s +0.0000 [-0.0018, +0.0019]  vsC2d +0.0002 [-0.0006, +0.0010]  (A4s 0.2126, C2d 0.2124, mkt 0.2095)
    weeks_10_18  n 1730 0.2110  vsA4s -0.0015 [-0.0030, +0.0000]  vsC2d +0.0001 [-0.0007, +0.0009]  (A4s 0.2125, C2d 0.2109, mkt 0.2072)
    changed      n  664 0.2138  vsA4s -0.0012 [-0.0035, +0.0011]  vsC2d -0.0012 [-0.0023, -0.0002]  (A4s 0.2150, C2d 0.2150, mkt 0.2072)
    unchanged    n 2786 0.2144  vsA4s -0.0007 [-0.0018, +0.0005]  vsC2d +0.0005 [-0.0000, +0.0010]  (A4s 0.2151, C2d 0.2139, mkt 0.2114)
    short_week   n  179 0.1986  vsA4s -0.0055 [-0.0098, -0.0011]  vsC2d -0.0018 [-0.0037, +0.0002]  (A4s 0.2041, C2d 0.2003, mkt 0.1893)
  E3b:
    weeks_1_4    n  751 0.2233  vsA4s -0.0010 [-0.0029, +0.0009]  vsC2d -0.0004 [-0.0016, +0.0007]  (A4s 0.2243, C2d 0.2237, mkt 0.2198)
    weeks_5_9    n  969 0.2127  vsA4s +0.0002 [-0.0017, +0.0020]  vsC2d +0.0003 [-0.0001, +0.0008]  (A4s 0.2126, C2d 0.2124, mkt 0.2095)
    weeks_10_18  n 1730 0.2106  vsA4s -0.0019 [-0.0034, -0.0005]  vsC2d -0.0004 [-0.0010, +0.0002]  (A4s 0.2125, C2d 0.2109, mkt 0.2072)
    changed      n  664 0.2139  vsA4s -0.0010 [-0.0034, +0.0013]  vsC2d -0.0010 [-0.0022, +0.0001]  (A4s 0.2150, C2d 0.2150, mkt 0.2072)
    unchanged    n 2786 0.2139  vsA4s -0.0012 [-0.0023, -0.0000]  vsC2d +0.0000 [-0.0004, +0.0004]  (A4s 0.2151, C2d 0.2139, mkt 0.2114)
    short_week   n  179 0.1991  vsA4s -0.0050 [-0.0092, -0.0007]  vsC2d -0.0012 [-0.0027, +0.0002]  (A4s 0.2041, C2d 0.2003, mkt 0.1893)

  E3c:
    weeks_1_4    n  751 0.2241  vsA4s -0.0002 [-0.0021, +0.0016]  vsC2d +0.0003 [-0.0002, +0.0009]  (A4s 0.2243, C2d 0.2237, mkt 0.2198)
    weeks_5_9    n  969 0.2125  vsA4s -0.0001 [-0.0020, +0.0019]  vsC2d +0.0001 [-0.0004, +0.0006]  (A4s 0.2126, C2d 0.2124, mkt 0.2095)
    weeks_10_18  n 1730 0.2108  vsA4s -0.0017 [-0.0030, -0.0003]  vsC2d -0.0001 [-0.0004, +0.0001]  (A4s 0.2125, C2d 0.2109, mkt 0.2072)
    changed      n  664 0.2150  vsA4s +0.0000 [-0.0022, +0.0022]  vsC2d +0.0000 [-0.0004, +0.0005]  (A4s 0.2150, C2d 0.2150, mkt 0.2072)
    unchanged    n 2786 0.2140  vsA4s -0.0012 [-0.0023, -0.0001]  vsC2d +0.0000 [-0.0002, +0.0003]  (A4s 0.2151, C2d 0.2139, mkt 0.2114)
    short_week   n  179 0.2005  vsA4s -0.0036 [-0.0073, +0.0003]  vsC2d +0.0001 [-0.0007, +0.0011]  (A4s 0.2041, C2d 0.2003, mkt 0.1893)
  E3abc:
    weeks_1_4    n  751 0.2240  vsA4s -0.0003 [-0.0024, +0.0019]  vsC2d +0.0003 [-0.0011, +0.0017]  (A4s 0.2243, C2d 0.2237, mkt 0.2198)
    weeks_5_9    n  969 0.2130  vsA4s +0.0004 [-0.0016, +0.0025]  vsC2d +0.0006 [-0.0003, +0.0015]  (A4s 0.2126, C2d 0.2124, mkt 0.2095)
    weeks_10_18  n 1730 0.2105  vsA4s -0.0020 [-0.0038, -0.0004]  vsC2d -0.0005 [-0.0017, +0.0006]  (A4s 0.2125, C2d 0.2109, mkt 0.2072)
    changed      n  664 0.2127  vsA4s -0.0023 [-0.0049, +0.0004]  vsC2d -0.0023 [-0.0040, -0.0007]  (A4s 0.2150, C2d 0.2150, mkt 0.2072)
    unchanged    n 2786 0.2145  vsA4s -0.0006 [-0.0019, +0.0007]  vsC2d +0.0005 [-0.0003, +0.0013]  (A4s 0.2151, C2d 0.2139, mkt 0.2114)
    short_week   n  179 0.1972  vsA4s -0.0069 [-0.0116, -0.0020]  vsC2d -0.0032 [-0.0060, -0.0002]  (A4s 0.2041, C2d 0.2003, mkt 0.1893)
  E4_all:
    weeks_1_4    n  751 0.2246  vsA4s +0.0003 [-0.0032, +0.0038]  vsC2d +0.0009 [-0.0022, +0.0039]  (A4s 0.2243, C2d 0.2237, mkt 0.2198)
    weeks_5_9    n  969 0.2112  vsA4s -0.0013 [-0.0046, +0.0023]  vsC2d -0.0012 [-0.0042, +0.0021]  (A4s 0.2126, C2d 0.2124, mkt 0.2095)
    weeks_10_18  n 1730 0.2131  vsA4s +0.0005 [-0.0020, +0.0030]  vsC2d +0.0021 [-0.0002, +0.0043]  (A4s 0.2125, C2d 0.2109, mkt 0.2072)
    changed      n  664 0.2148  vsA4s -0.0002 [-0.0043, +0.0039]  vsC2d -0.0002 [-0.0039, +0.0034]  (A4s 0.2150, C2d 0.2150, mkt 0.2072)
    unchanged    n 2786 0.2151  vsA4s +0.0000 [-0.0020, +0.0021]  vsC2d +0.0012 [-0.0005, +0.0029]  (A4s 0.2151, C2d 0.2139, mkt 0.2114)
    short_week   n  179 0.2021  vsA4s -0.0020 [-0.0107, +0.0066]  vsC2d +0.0018 [-0.0061, +0.0094]  (A4s 0.2041, C2d 0.2003, mkt 0.1893)
  E4w:
    weeks_1_4    n  751 0.2240  vsA4s -0.0003 [-0.0021, +0.0014]  vsC2d +0.0002 [-0.0002, +0.0007]  (A4s 0.2243, C2d 0.2237, mkt 0.2198)
    weeks_5_9    n  969 0.2125  vsA4s -0.0001 [-0.0019, +0.0018]  vsC2d +0.0001 [-0.0004, +0.0007]  (A4s 0.2126, C2d 0.2124, mkt 0.2095)
    weeks_10_18  n 1730 0.2115  vsA4s -0.0010 [-0.0025, +0.0005]  vsC2d +0.0005 [-0.0002, +0.0013]  (A4s 0.2125, C2d 0.2109, mkt 0.2072)
    changed      n  664 0.2156  vsA4s +0.0006 [-0.0017, +0.0029]  vsC2d +0.0006 [-0.0004, +0.0017]  (A4s 0.2150, C2d 0.2150, mkt 0.2072)
    unchanged    n 2786 0.2142  vsA4s -0.0009 [-0.0020, +0.0003]  vsC2d +0.0003 [-0.0002, +0.0008]  (A4s 0.2151, C2d 0.2139, mkt 0.2114)
    short_week   n  179 0.1999  vsA4s -0.0042 [-0.0084, -0.0002]  vsC2d -0.0004 [-0.0016, +0.0005]  (A4s 0.2041, C2d 0.2003, mkt 0.1893)

  E5:
    weeks_1_4    n  751 0.2233  vsA4s -0.0010 [-0.0029, +0.0009]  vsC2d -0.0004 [-0.0016, +0.0007]  (A4s 0.2243, C2d 0.2237, mkt 0.2198)
    weeks_5_9    n  969 0.2127  vsA4s +0.0002 [-0.0017, +0.0020]  vsC2d +0.0003 [-0.0001, +0.0008]  (A4s 0.2126, C2d 0.2124, mkt 0.2095)
    weeks_10_18  n 1730 0.2106  vsA4s -0.0019 [-0.0034, -0.0005]  vsC2d -0.0004 [-0.0010, +0.0002]  (A4s 0.2125, C2d 0.2109, mkt 0.2072)
    changed      n  664 0.2139  vsA4s -0.0010 [-0.0034, +0.0013]  vsC2d -0.0010 [-0.0022, +0.0001]  (A4s 0.2150, C2d 0.2150, mkt 0.2072)
    unchanged    n 2786 0.2139  vsA4s -0.0012 [-0.0023, -0.0000]  vsC2d +0.0000 [-0.0004, +0.0004]  (A4s 0.2151, C2d 0.2139, mkt 0.2114)
    short_week   n  179 0.1991  vsA4s -0.0050 [-0.0092, -0.0007]  vsC2d -0.0012 [-0.0027, +0.0002]  (A4s 0.2041, C2d 0.2003, mkt 0.1893)
  E5m:
    weeks_1_4    n  751 0.2233  vsA4s -0.0010 [-0.0026, +0.0006]  vsC2d -0.0004 [-0.0015, +0.0006]  (A4s 0.2243, C2d 0.2237, mkt 0.2198)
    weeks_5_9    n  969 0.2120  vsA4s -0.0006 [-0.0021, +0.0010]  vsC2d -0.0004 [-0.0011, +0.0003]  (A4s 0.2126, C2d 0.2124, mkt 0.2095)
    weeks_10_18  n 1730 0.2111  vsA4s -0.0014 [-0.0026, -0.0002]  vsC2d +0.0002 [-0.0002, +0.0006]  (A4s 0.2125, C2d 0.2109, mkt 0.2072)
    changed      n  664 0.2138  vsA4s -0.0012 [-0.0030, +0.0006]  vsC2d -0.0012 [-0.0022, -0.0002]  (A4s 0.2150, C2d 0.2150, mkt 0.2072)
    unchanged    n 2786 0.2141  vsA4s -0.0010 [-0.0019, -0.0001]  vsC2d +0.0001 [-0.0003, +0.0005]  (A4s 0.2151, C2d 0.2139, mkt 0.2114)
    short_week   n  179 0.2001  vsA4s -0.0040 [-0.0073, -0.0007]  vsC2d -0.0002 [-0.0016, +0.0011]  (A4s 0.2041, C2d 0.2003, mkt 0.1893)
  E6:
    weeks_1_4    n  751 0.2237  vsA4s -0.0005 [-0.0020, +0.0008]  vsC2d +0.0000 [-0.0010, +0.0011]  (A4s 0.2243, C2d 0.2237, mkt 0.2198)
    weeks_5_9    n  969 0.2121  vsA4s -0.0004 [-0.0020, +0.0012]  vsC2d -0.0003 [-0.0012, +0.0006]  (A4s 0.2126, C2d 0.2124, mkt 0.2095)
    weeks_10_18  n 1730 0.2120  vsA4s -0.0005 [-0.0019, +0.0008]  vsC2d +0.0010 [+0.0003, +0.0017]  (A4s 0.2125, C2d 0.2109, mkt 0.2072)
    changed      n  664 0.2156  vsA4s +0.0006 [-0.0015, +0.0027]  vsC2d +0.0006 [-0.0008, +0.0020]  (A4s 0.2150, C2d 0.2150, mkt 0.2072)
    unchanged    n 2786 0.2143  vsA4s -0.0008 [-0.0017, +0.0002]  vsC2d +0.0004 [-0.0001, +0.0009]  (A4s 0.2151, C2d 0.2139, mkt 0.2114)
    short_week   n  179 0.2002  vsA4s -0.0038 [-0.0073, -0.0003]  vsC2d -0.0001 [-0.0017, +0.0015]  (A4s 0.2041, C2d 0.2003, mkt 0.1893)
  E6b:
    weeks_1_4    n  751 0.2238  vsA4s -0.0005 [-0.0019, +0.0009]  vsC2d +0.0001 [-0.0007, +0.0010]  (A4s 0.2243, C2d 0.2237, mkt 0.2198)
    weeks_5_9    n  969 0.2118  vsA4s -0.0008 [-0.0023, +0.0008]  vsC2d -0.0006 [-0.0015, +0.0003]  (A4s 0.2126, C2d 0.2124, mkt 0.2095)
    weeks_10_18  n 1730 0.2121  vsA4s -0.0005 [-0.0017, +0.0008]  vsC2d +0.0011 [+0.0004, +0.0018]  (A4s 0.2125, C2d 0.2109, mkt 0.2072)
    changed      n  664 0.2156  vsA4s +0.0006 [-0.0013, +0.0025]  vsC2d +0.0006 [-0.0006, +0.0018]  (A4s 0.2150, C2d 0.2150, mkt 0.2072)
    unchanged    n 2786 0.2143  vsA4s -0.0008 [-0.0017, +0.0001]  vsC2d +0.0004 [-0.0001, +0.0009]  (A4s 0.2151, C2d 0.2139, mkt 0.2114)
    short_week   n  179 0.2005  vsA4s -0.0036 [-0.0068, -0.0002]  vsC2d +0.0002 [-0.0015, +0.0020]  (A4s 0.2041, C2d 0.2003, mkt 0.1893)

Coefficients (last DEV refit; range over the DEV refits):
  C2d (2019 fit, n 4600): intercept -0.01409 [-0.0513, -0.0141], elo_logit +0.4325 [+0.176, +0.496], kf_margin +0.08294 [+0.0684, +0.114], qb_delta_diff +3.495 [+2.59, +3.67]
  E1_C2d_margin_logit (2019 fit, n 4600): intercept -0.08828 [-0.423, -0.00218], elo_logit +3.071 [+2.62, +4.56], kf_margin +0.6105 [+0.342, +0.704], qb_delta_diff +26.06 [+21, +27.4], conv_a +3.352e-15 [-5.38e-15, +5.6e-15], conv_b +1 [+1, +1], sigma +13.47 [+13.3, +13.8], cal_a -0.001042 [-0.0189, +0.00984], cal_b +0.1375 [+0.127, +0.138]
  E2a (2019 fit, n 4600): intercept -0.01612 [-0.0507, -0.0149], elo_logit +0.4276 [+0.176, +0.493], kf_margin +0.08364 [+0.0676, +0.114], qb_delta_diff_v2a +3.516 [+2.58, +3.72]
  E3a (2019 fit, n 4600): intercept -0.002995 [-0.041, +0.0046], elo_logit +0.3995 [+0.151, +0.465], kf_margin +0.08314 [+0.0693, +0.115], qb_delta_diff +3.373 [+2.48, +3.53], qb_new_diff -0.05942 [-0.128, +0.00584], qb_new_x_wk -0.08543 [-0.116, +0.0767]
  E3b (2019 fit, n 4600): intercept -0.01847 [-0.0511, -0.0162], elo_logit +0.4438 [+0.181, +0.501], kf_margin +0.08378 [+0.0699, +0.115], qb_delta_diff +3.439 [+2.61, +3.63], coach_new_diff -0.15 [-0.252, -0.025], coach_new_x_wk +0.4386 [+0.0817, +0.442]
  E4_all (2019 fit, n 4600): intercept -0.2024 [-0.379, -0.193], elo_logit +0.3982 [+0.148, +0.448], kf_margin +0.08708 [+0.0711, +0.117], qb_delta_diff +3.522 [+2.57, +3.65], travel_diff -0.02427 [-0.1, +0.0788], tz_diff -0.01938 [-0.15, -0.00504], body_early_diff -0.1226 [-0.395, -0.109], body_late_diff -0.2134 [-0.617, -0.213], rest_diff -0.009368 [-0.0929, +0.066], bye_diff +0.329 [-0.118, +0.841], alt_diff -0.1911 [-0.765, -0.0228], indoor -0.04502 [-0.168, +0.018], turf +0.1505 [+0.0343, +0.272], surface_mm_diff -0.1292 [-0.291, -0.00137], dome_cold_diff -0.06752 [-0.56, -0.0675]
  E5 (2019 fit, n 4600): intercept -0.01847 [-0.0511, -0.0162], elo_logit +0.4438 [+0.181, +0.501], kf_margin +0.08378 [+0.0699, +0.115], qb_delta_diff +3.439 [+2.61, +3.63], coach_new_diff -0.15 [-0.252, -0.025], coach_new_x_wk +0.4386 [+0.0817, +0.442]
  E5m (2019 fit, n 4600): intercept -0.0792 [-0.401, +0.00823], elo_logit +3.006 [+2.5, +4.47], kf_margin +0.6168 [+0.349, +0.711], qb_delta_diff +26.05 [+21.1, +27.5], coach_new_diff -0.6574 [-1.41, -0.31], coach_new_x_wk +1.126 [+0.405, +2.37], conv_a -7.267e-16 [-4.69e-15, +6.34e-15], conv_b +1 [+1, +1], sigma +13.47 [+13.3, +13.8], cal_a -0.00116 [-0.0186, +0.00974], cal_b +0.1377 [+0.127, +0.138]
  E6 (2019 fit, n 4096): intercept +0.0204 [-0.0456, +0.0204], E5 +0.5047 [+0.311, +0.505], C2d +0.3846 [+0.168, +0.577], Elo +0.09558 [+0.0428, +0.393], A4s +0.07126 [+0, +0.272]
  E6b (2019 fit, n 4096): intercept +0.02375 [-0.0435, +0.0238], A4s +0.009748 [+0, +0.155], C2d +0.3644 [+0.00768, +0.469], Elo +0.06107 [+0, +0.315], E1_C2d_margin_logit +0.6172 [+0.514, +0.726]

Timing: features 10.1s, ladder 1.3s, total 21.8s

32 runs written to data/raw/ml/_train_all_runs/

[11. M8 game model v2: 33s]

**Retrained vs the committed development record**: 35 of 35 runs match (tolerance max(5e-05, 0.2% of the record) on every metric).

No holdout result exists for M8 by design: nothing beat C2d on the development seasons.

## 12. The 2026 production models

Fits the models that run live this season, the way `scripts/ml_predict.py` does, on every completed season through
2025: **A4s** (the headline win probability), the **margin model**, and the **C2d shadow model**. Each fit first
re-fits the last development season and stops unless it reproduces the committed coefficients. Then it predicts every
unplayed 2026 game and simulates the rest of the season for playoff odds. **Nothing is written**: not the ledger, not
`experiments/live/`, not `site/data/`.

In [15]:
import ml_predict as mp
import export_site as xs
from nflelo.ml import live, live_features
from nflelo.ml.sim import season as sim_season

with section("12a. 2026 models: fit"):
    # ml_predict reads Elo from outputs/ (written by build.py). Point it at the in-memory rebuild instead.
    elo_out = ELO.drop(columns=["source"]).copy()
    for c in ["home_pre", "away_pre", "home_post", "away_post"]:
        elo_out[c] = elo_out[c].round(2)
    xs.load_elo = lambda: elo_out
    import build as build_script
    RATINGS = build_script.current_ratings(ELO, config.DEFAULT_CONFIG, ELO_STATE)
    xs.load_ratings = lambda: RATINGS

    NOW = pd.Timestamp.now(tz="UTC").floor("s")
    pbp26, sched26, games26 = mp.load(CURRENT)               # games26 = the in-memory rebuild
    mp.check_elo_fresh(sched26, games26, elo_out, CURRENT)   # Elo includes every finished game
    MODEL = mp.fit_model(CURRENT, pbp26, sched26, games26)
    MARGIN = mp.fit_margin_model(CURRENT, pbp26, sched26, games26)
    SHADOW = mp.fit_shadow_model(CURRENT, pbp26, sched26, games26)
    VERSION = mp.combined_version(MODEL, MARGIN)

coef = pd.DataFrame({"A4s": {"intercept": MODEL["intercept"], **MODEL["coef"]},
                     "C2d shadow": {"intercept": SHADOW["intercept"], **SHADOW["coef"]}})
display(coef.round(4))
print(f"A4s {MODEL['model_version']}: trained on REG {MODEL['train']['seasons'][0]}-{MODEL['train']['seasons'][1]} "
      f"(n = {MODEL['train']['n_games']})")
print(f"margin {MARGIN['version']}: sigma {MARGIN['fit']['sigma']:.2f}, shape {MARGIN['shape']}")

reproduction check: 2025 coefficients match experiments/runs/20261003T215950Z_m3_signoff_A4s.json (max |diff| 6.7e-16)

margin reproduction check: 2019 fit matches experiments/runs/20261005T021003Z_m4_margin_keynum.json (max |diff| 2.8e-14)

shadow reproduction check: 2019 C2d coefficients match experiments/runs/20261005T062809Z_m3b_C2d.json (max |diff| 1.7e-16)

[12a. 2026 models: fit: 12s]

                   A4s  C2d shadow
intercept       0.0094     -0.0538
elo_logit       0.7967      0.5336
adj_epa_margin  1.1489         NaN
qb_delta_diff   3.6999      3.6253
kf_margin          NaN      0.0643

A4s A4s-2026-e25b31e2: trained on REG 2001-2025 (n = 6471)
margin M-2026-4d6cbdab: sigma 13.26, shape keynum

In [16]:
with section("12b. 2026 models: predict + simulate"):
    pred = mp.predict(CURRENT, NOW, pbp26, sched26, games26, MODEL, MARGIN)
    sp = mp.shadow_predict(SHADOW, pred, pbp26, sched26, CURRENT, NOW)
    nxt = live_features.next_week(sched26[sched26["season"] == CURRENT], NOW)

    SIM_DIR = CAPTURE / "sim"
    SIM_DIR.mkdir(exist_ok=True)
    n_sims = sim_season.DEFAULT_SIMS if FULL else 4000
    odds = mp.run_sim(CURRENT, NOW, pbp26, sched26, games26, MARGIN, VERSION, SIM_DIR, n_sims)

view = pred.join(sp[["p_home_shadow", "kf_margin"]])
wk_last = nxt if nxt is not None else int(view["game_week"].max())
view = view[view["game_week"] <= wk_last].sort_values("kickoff_utc")     # rest of the current week plus the next slate
tbl = pd.DataFrame({
    "week": view["game_week"], "kickoff (ET)": view["kickoff_utc"].dt.tz_convert("America/New_York").dt.strftime("%a %b %d %H:%M"),
    "game": view["away_team"] + " @ " + view["home_team"],
    "NFLELO model: home win %": (100 * view["p_home_model"]).round(1),
    "shadow (C2d) %": (100 * view["p_home_shadow"]).round(1),
    "Elo %": (100 * view["p_home_elo"]).round(1),
    "Vegas % (benchmark)": (100 * view["p_home_market"]).round(1),
    "model spread (home)": view["spread_model"].round(1),
    "QB news": view["qb_delta_diff"].round(3),
})
display(Markdown(f"**This week's predictions** (as of {NOW:%Y-%m-%d %H:%M} UTC; {len(pred)} unplayed regular-season games; "
                 f"showing weeks {int(view['game_week'].min())}-{wk_last}). Vegas is a benchmark only and never an input."))
display(tbl.reset_index(drop=True).style.hide(axis="index"))

simulation: 20,000 seasons, 180 games left, tau_rest 4.5, seed 1792470396; state 0.9s, simulate 3.9s (draws 0.2s, tiebreakers 3.6s, bracket 0.0s); appended 32 rows to /Users/walker_tracy/Desktop/Old Projects/NFLELO/data/raw/ml/_train_all_runs/sim/sim_2026.csv
Playoff odds, top 5:    SF 97% (SB 15.3%); MIN 91% (SB 8.5%); BUF 90% (SB 10.1%); KC 88% (SB 7.0%); JAX 86% (SB 8.0%)
Playoff odds, bottom 5: NYJ 9% (SB 0.2%); ARI 6% (SB 0.2%); TEN 1% (SB 0.0%); MIA 1% (SB 0.0%); LAC 1% (SB 0.0%)

[12b. 2026 models: predict + simulate: 6s]

**This week's predictions** (as of 2026-10-20 04:26 UTC; 180 unplayed regular-season games; showing weeks 6-7). Vegas is a benchmark only and never an input.

In [17]:
o = odds.sort_values(["playoffs", "win_sb"], ascending=False)
cols = {"wins_mean": "proj. wins", "playoffs": "make playoffs %", "win_div": "win division %", "seed1": "top seed %", "win_sb": "win title %"}
t = o[[c for c in cols if c in o.columns]].rename(columns=cols)
for c in t.columns:
    if "%" in c:
        t[c] = (100 * t[c]).round(1)
t["proj. wins"] = t["proj. wins"].round(1)
display(Markdown(f"**Playoff odds**: {n_sims:,} simulated seasons from the current standings and ratings "
                 f"(model {VERSION})."))
display(t.head(12))

**Playoff odds**: 20,000 simulated seasons from the current standings and ratings (model A4s-2026-e25b31e2+M-2026-4d6cbdab).

      proj. wins  make playoffs %  top seed %  win title %
team
SF          13.2             96.6        50.9         15.3
MIN         12.1             90.9        28.5          8.5
BUF         11.9             90.0        26.2         10.1
KC          11.6             87.6        24.0          7.0
JAX         11.3             86.4        13.3          8.0
NE          10.5             77.1        10.3          6.2
DEN         10.7             75.4        11.4          5.7
SEA         10.3             72.0         5.0          8.6
CHI         10.2             67.3         4.6          5.0
CAR          9.0             61.7         2.6          2.2
CIN         10.1             59.9         5.1          3.1
PIT         10.0             58.3         4.1          2.7

## 13. Timing and integrity

Wall-clock time per section, a roll-up of every retrained development run against the committed record, and the
checks that this notebook changed nothing tracked.

In [18]:
total = sum(SECTION_SECONDS.values())
timing = pd.DataFrame({"section": list(SECTION_SECONDS), "seconds": [round(v, 1) for v in SECTION_SECONDS.values()],
                       "minutes": [round(v / 60, 1) for v in SECTION_SECONDS.values()]})
timing.loc[len(timing)] = ["TOTAL (sections)", round(total, 1), round(total / 60, 1)]
display(Markdown(f"**Timing, mode `{MODE}`**"))
display(timing.style.hide(axis="index"))

**Timing, mode `full`**

In [19]:
# Roll-up: every run this notebook retrained that has a committed development record.
summary = match_table(ALL_RECS, title="All retrained development runs vs the committed record")
bad = summary[~summary["status"].isin(["OK"])]
if len(bad):
    display(Markdown("**Runs that differ from, or have no, committed record:**"))
    display(bad)

**All retrained development runs vs the committed record**: 126 of 126 runs match (tolerance max(5e-05, 0.2% of the record) on every metric).

In [20]:
# Integrity checks: nothing tracked changed, the registry is untouched, no run touched the locked seasons.
new_changes = git_dirty() - GIT_AT_START
allowed = {"notebooks/train_all_models.ipynb", "scripts/train_all.sh", ".gitignore"}
unexpected = sorted(l for l in new_changes if l[3:] not in allowed)
runs_now = sorted(p.name for p in REAL_RUNS.glob("*.json"))
assert runs_now == RUNS_AT_START, "the committed run registry changed"
assert not unexpected, f"unexpected git changes: {unexpected}"
assert not any(r.get("holdout") for r in ALL_RECS), "a retrained run touched the locked holdout seasons"
print(f"registry files: {len(runs_now)} (unchanged)")
print(f"retrained run records captured outside the registry: {len(list(CAPTURE.glob('*.json')))} in {CAPTURE.relative_to(ROOT)}/")
print("new git changes from this run:", sorted(new_changes) or "none")
print("holdout seasons touched by any retrained run: none")

registry files: 167 (unchanged)
retrained run records captured outside the registry: 126 in data/raw/ml/_train_all_runs/
new git changes from this run: none
holdout seasons touched by any retrained run: none